import SwiftUI

struct LabelsView: View {
    @Bindable var model: LabelsModel
    @Environment(\.colorScheme) private var scheme
    @State private var createOpen = false
    @FocusState private var focused: Field?
    enum Field: Hashable { case createName, editName }
    private let colors = WorkspaceTheme.palette
    var body: some View {
        ScrollView { VStack(alignment: .leading, spacing: 18) {
            HStack { VStack(alignment: .leading, spacing: 4) { Text("WORKSPACE").font(.caption.weight(.semibold)); Text("Labels").font(.largeTitle.bold()) }; Spacer(); Button { model.beginCreate(); createOpen = true } label: { Image(systemName: "plus").frame(width: 44, height: 44) }.buttonStyle(WorkspaceButton(primary: true)).accessibilityLabel("Add label").accessibilityIdentifier("labels.add") }
            Text("Create reusable labels and choose where they appear. A label can be used in more than one place.").foregroundStyle(WorkspaceTheme.muted(scheme))
            if let error = model.error { Text(error).font(.subheadline).foregroundStyle(WorkspaceTheme.danger(scheme)).accessibilityLabel(error) }
            VStack(alignment: .leading, spacing: 14) { HStack { Text("Your labels").font(.title3.bold()); Spacer(); Text("\(model.labels.count) total").foregroundStyle(WorkspaceTheme.muted(scheme)) }; if model.loading { Text("Loading…").foregroundStyle(WorkspaceTheme.muted(scheme)) } else if model.sortedLabels.isEmpty { Text("No labels yet. Add one above to get started.").foregroundStyle(WorkspaceTheme.muted(scheme)) } else { LazyVStack(alignment: .leading, spacing: 0) { ForEach(model.sortedLabels) { row($0) } } } }.padding(16).background(WorkspaceTheme.surface(scheme), in: RoundedRectangle(cornerRadius: 8)).overlay(RoundedRectangle(cornerRadius: 8).stroke(WorkspaceTheme.border(scheme)))
        }.padding(16).frame(maxWidth: 1200, alignment: .leading) }
        .refreshable { await model.load() }.task { if !model.loaded { await model.load() } }
        .sheet(isPresented: $createOpen) { editor(title: "Add a label", draft: $model.draft, submit: { _ = await model.create(); if model.error == nil { createOpen = false } }, cancel: { createOpen = false }) }
        .confirmationDialog("Remove “\(model.deleteCandidate?.name ?? "")”?", isPresented: Binding(get: { model.deleteCandidate != nil }, set: { if !$0 { model.cancelRemove() } }), titleVisibility: .visible) { Button("Remove", role: .destructive) { Task { await model.confirmRemove() } }; Button("Cancel", role: .cancel) {} } message: { Text("Labels in use must be unassigned first.") }
        .confirmationDialog("“\(model.deleteAssignmentsCandidate?.name ?? "")” has assignments. Remove the label and its assignments?", isPresented: Binding(get: { model.deleteAssignmentsCandidate != nil }, set: { if !$0 { model.cancelRemove() } }), titleVisibility: .visible) { Button("Remove label and assignments", role: .destructive) { Task { await model.confirmRemoveAssignments() } }; Button("Cancel", role: .cancel) {} } message: { Text("This keeps the assigned notes, sessions, and calendar days.") }
    }
    @ViewBuilder private func row(_ label: KBLabel) -> some View { if model.editingID == label.id, model.editingDraft != nil { editor(title: "Edit \(label.name)", draft: Binding(get: { model.editingDraft ?? LabelDraft(label) }, set: { model.editingDraft = $0 }), submit: { _ = await model.saveEdit() }, cancel: { model.cancelEdit() }) } else { HStack { Circle().fill(WorkspaceTheme.color(label.color ?? colors[0])).frame(width: 14, height: 14).accessibilityHidden(true); Text(label.name).bold().lineLimit(2); Text(label.scopes.map(\.title).joined(separator: " · ")).foregroundStyle(WorkspaceTheme.muted(scheme)).lineLimit(2); Spacer(); Button("Edit") { model.beginEdit(label) }.accessibilityIdentifier("labels.edit.\(label.id)"); Button("Remove") { model.requestRemove(label) }.foregroundStyle(WorkspaceTheme.danger(scheme)).accessibilityIdentifier("labels.remove.\(label.id)") }.padding(.vertical, 8).accessibilityElement(children: .contain) } }
    @ViewBuilder private func editor(title: String, draft: Binding<LabelDraft>, submit: @escaping () async -> Void, cancel: @escaping () -> Void) -> some View { NavigationStack { Form { Section { TextField("Name", text: draft.name).focused($focused, equals: title.hasPrefix("Add") ? .createName : .editName).submitLabel(.done).onSubmit { Task { await submit() } } }.accessibilityIdentifier("labels.name"); Section("Color") { LazyVGrid(columns: Array(repeating: GridItem(.flexible(), spacing: 8), count: 5)) { ForEach(colors, id: \.self) { color in Button { draft.color.wrappedValue = color } label: { Circle().fill(WorkspaceTheme.color(color)).frame(width: 34, height: 34).overlay(draft.wrappedValue.color == color ? Circle().stroke(WorkspaceTheme.text(scheme), lineWidth: 3) : nil) }.frame(minWidth: 44, minHeight: 44).accessibilityLabel("Choose \(color) color").accessibilityAddTraits(draft.wrappedValue.color == color ? .isSelected : []) } } }; Section("Show in") { ForEach(LabelScope.allCases) { scope in Toggle(scope.title, isOn: Binding(get: { draft.wrappedValue.scopes.contains(scope) }, set: { if $0 { draft.wrappedValue.scopes.insert(scope) } else { draft.wrappedValue.scopes.remove(scope) } })) } }; if let error = model.error { Text(error).foregroundStyle(WorkspaceTheme.danger(scheme)) } }.navigationTitle(title).toolbar { ToolbarItem(placement: .cancellationAction) { Button("Cancel", action: cancel) }; ToolbarItem(placement: .confirmationAction) { Button(title.hasPrefix("Add") ? "Add label" : "Save") { Task { await submit() } }.disabled(model.busy) } } }.presentationDetents([.medium, .large]).onAppear { focused = title.hasPrefix("Add") ? .createName : .editName } }
}
