import SwiftUI

struct ReportsView: View {
    @ObservedObject var model: ReportsModel
    @Environment(\.colorScheme) private var scheme
    private let duration: (Int64) -> String = { seconds in
        let hours = seconds / 3600; let minutes = (seconds % 3600) / 60
        if seconds == 0 { return "00:00" }
        return hours > 0 ? "\(hours)h \(minutes)m" : "\(minutes)m"
    }
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 18) {
                Text("Reports").font(.largeTitle.bold()).accessibilityAddTraits(.isHeader)
                HStack { Text("SUMMARY").font(.caption.weight(.bold)); Spacer(); if model.refreshing { Text("Updating report…").font(.caption).accessibilityAddTraits(.updatesFrequently) } }
                if model.report == nil {
                    if model.loading {
                        skeleton
                    } else {
                        ProgressView("Loading report…")
                            .frame(maxWidth: .infinity)
                            .padding(.vertical, 40)
                    }
                } else {
                    content
                }
            }.padding(16).frame(maxWidth: 1200, alignment: .leading).frame(maxWidth: .infinity)
        }.refreshable { await model.retry() }
        .task { await model.load() }
        .overlay(alignment: .top) { if let error = model.error { HStack { Label(error, systemImage: "exclamationmark.triangle"); Spacer(); Button("Try again") { Task { await model.retry() } }.accessibilityIdentifier("reports.retry") }.padding(12).background(.thinMaterial).accessibilityElement(children: .contain) } }
        .accessibilityIdentifier("reports.page")
    }
    private var skeleton: some View { VStack(alignment: .leading, spacing: 14) { ProgressView("Loading report…"); RoundedRectangle(cornerRadius: 8).fill(.secondary.opacity(0.15)).frame(height: 180); ForEach(0..<3, id: \.self) { _ in RoundedRectangle(cornerRadius: 5).fill(.secondary.opacity(0.12)).frame(height: 32) } }.accessibilityElement(children: .combine) }
    private var content: some View { VStack(alignment: .leading, spacing: 18) {
        Text("Tracked time").font(.headline); Text(duration(model.report?.totalSeconds ?? 0)).font(.system(size: 32, weight: .bold, design: .rounded)).monospacedDigit()
        controls
        if let report = model.report, report.days.isEmpty {
            Text("No report data for this period.").foregroundStyle(.secondary).padding(.vertical, 30)
            if report.sankey != nil { sankeyControl }
        } else {
            chart; breakdown
            if model.report?.sankey != nil { sankeyControl }
            calendarSummary
        }
    } }
    private var sankeyControl: some View { Group { Button(model.showSankey ? "Show bar chart" : "Show Sankey") { model.showSankey.toggle() }.frame(minHeight: 44); if model.showSankey { sankey } } }
    private var controls: some View { VStack(alignment: .leading, spacing: 10) {
        HStack { Button("Previous") { Task { await model.shift(-1) } }.frame(minHeight: 44); Button("Next") { Task { await model.shift(1) } }.frame(minHeight: 44); Spacer(); Menu("Preset") { ForEach(ReportDateMath.presets, id: \.self) { preset in Button(preset) { Task { await model.setPreset(preset) } } } } }
        Picker("Aggregation", selection: Binding(get: { model.query.aggregation }, set: { value in Task { await model.setAggregation(value) } })) { ForEach(ReportAggregation.allCases) { Text($0.title).tag($0) } }.pickerStyle(.segmented).accessibilityIdentifier("reports.aggregation")
        HStack { DatePicker("Start", selection: dateBinding(start: true), displayedComponents: .date); DatePicker("End", selection: dateBinding(start: false), displayedComponents: .date) }.labelsHidden().accessibilityElement(children: .contain)
        Text("\(model.query.startDate) – \(model.query.endDate)").font(.subheadline).monospacedDigit(); if let rangeError = model.rangeError { Text(rangeError).font(.caption).foregroundStyle(.red).accessibilityAddTraits(.isStaticText) }
        filterMenu(title: "Paths", options: model.pathOptions, selected: model.query.pathIDs, toggle: model.togglePath, clear: model.clearPaths)
        filterMenu(title: "Labels", options: model.labelOptions.map { Path(id: $0.id, name: $0.name, description: nil, status: "ACTIVE", color: $0.color) }, selected: model.query.labelIDs, toggle: model.toggleLabel, clear: model.clearLabels)
    }.accessibilityElement(children: .contain) }
    private func dateBinding(start: Bool) -> Binding<Date> { Binding(get: { ReportDateMath.date(start ? model.query.startDate : model.query.endDate) ?? Date() }, set: { value in let date = ReportDateMath.iso(value); Task { await model.setRange(start: start ? date : model.query.startDate, end: start ? model.query.endDate : date) } }) }
    private func filterMenu(title: String, options: [Path], selected: [UUID], toggle: @escaping (UUID) async -> Void, clear: @escaping () async -> Void) -> some View { let key = title.lowercased(); return VStack(alignment: .leading, spacing: 4) { HStack { Text(title).font(.subheadline.weight(.semibold)); if !selected.isEmpty { Button("Clear") { Task { await clear() } }.font(.caption).accessibilityIdentifier("reports.\(key).clear") }; Spacer(); Menu("Choose \(key)") { ForEach(options) { option in Button { Task { await toggle(option.id) } } label: { Label(option.name, systemImage: selected.contains(option.id) ? "checkmark.square" : "square") } } }.accessibilityIdentifier("reports.\(key).filter") }.frame(minHeight: 44); if !selected.isEmpty { HStack { ForEach(selected.compactMap { id in options.first(where: { $0.id == id }) }, id: \.id) { option in HStack(spacing: 3) { Text(option.name).lineLimit(2); Button("Remove \(option.name)", systemImage: "xmark.circle.fill") { Task { await toggle(option.id) } }.labelStyle(.iconOnly).accessibilityIdentifier("reports.\(key).remove.\(option.id.uuidString)") }.padding(.horizontal, 8).padding(.vertical, 5).background(.secondary.opacity(0.12), in: Capsule()) } }.fixedSize(horizontal: false, vertical: true) } } }
    private var chart: some View { VStack(alignment: .leading, spacing: 10) { HStack { Text(model.showSankey ? "TIME FLOW" : "Activity").font(.headline); Spacer(); Button("Trendline: \(model.trendline.title)") { model.trendline = ReportTrendline.allCases[(ReportTrendline.allCases.firstIndex(of: model.trendline)! + 1) % ReportTrendline.allCases.count] }.frame(minHeight: 44).accessibilityValue(model.trendline.title).accessibilityHint("Cycles through Off, Linear, and Parabolic").accessibilityAddTraits(model.trendline == .off ? [] : .isSelected).accessibilityIdentifier("reports.trendline") }; if model.showSankey { EmptyView() } else { let buckets = ReportCalculations.buckets(model.report!, query: model.query); ForEach(buckets) { bucket in HStack { Text(bucket.label).frame(width: 100, alignment: .leading); GeometryReader { proxy in RoundedRectangle(cornerRadius: 3).fill(WorkspaceTheme.accent(scheme)).frame(width: max(4, proxy.size.width * CGFloat(bucket.seconds) / CGFloat(max(1, model.report!.totalSeconds)))) }.frame(height: 18); Text(duration(bucket.seconds)).monospacedDigit().frame(width: 70, alignment: .trailing) }.frame(height: 28).accessibilityElement(children: .combine).accessibilityLabel(bucketAccessibilityLabel(bucket)) }; let trend = ReportCalculations.trend(buckets, mode: model.trendline); if !trend.isEmpty { Text("\(model.trendline.title) trend: \(trend.map { duration($0.1) }.joined(separator: ", "))").font(.caption).foregroundStyle(.secondary).accessibilityLabel("\(model.trendline.title) trend values \(trend.map { duration($0.1) }.joined(separator: ", "))") } } }.padding(14).background(.secondary.opacity(0.08), in: RoundedRectangle(cornerRadius: 10)) }
    private func bucketAccessibilityLabel(_ bucket: ReportBucket) -> String { let categories = bucket.categories.map { "\($0.label): \(duration($0.seconds))" }.joined(separator: ", "); return "\(bucket.label), total \(duration(bucket.seconds)), \(categories)" }
    private var sankey: some View { Group { if let sankey = model.report?.sankey, !sankey.nodes.isEmpty { VStack(alignment: .leading, spacing: 10) { Text("Path timing by \(sankey.granularity.lowercased())").font(.subheadline); Text("\(sankey.links.count) tracked flow\(sankey.links.count == 1 ? "" : "s")").font(.caption).foregroundStyle(.secondary); ScrollView(.horizontal) { HStack(alignment: .top, spacing: 24) { ForEach(Array(Dictionary(grouping: sankey.nodes, by: \.depth).keys.sorted()), id: \.self) { depth in VStack(alignment: .leading) { Text("Stage \(depth + 1)").font(.caption.bold()); ForEach(sankey.nodes.filter { $0.depth == depth }) { node in Text("\(node.label) · \(duration(node.value))").padding(8).background(.secondary.opacity(0.12), in: RoundedRectangle(cornerRadius: 6)).accessibilityLabel("\(node.bucketLabel), \(node.pathLabel), \(duration(node.value))") } } } }.frame(minWidth: 620, alignment: .leading).padding(.vertical, 8) }; VStack(alignment: .leading, spacing: 4) { ForEach(Array(sankey.links.enumerated()), id: \.offset) { _, link in Text("\(link.sourceLabel) to \(link.targetLabel) · \(duration(link.value))").font(.caption).accessibilityLabel("Flow from \(link.sourceLabel) to \(link.targetLabel), \(duration(link.value))") } } } } else { Text("No tracked time to show in this flow.").foregroundStyle(.secondary) } }.accessibilityElement(children: .contain) }
    private var calendarSummary: some View { Group { if model.query.aggregation == .day, let report = model.report, report.days.contains(where: { $0.calendarNote != nil || !$0.calendarLabels.isEmpty }) { VStack(alignment: .leading, spacing: 8) { HStack { Text("DAILY RECORDS").font(.caption.weight(.bold)); Spacer(); Button(model.showCalendarInputs ? "Hide calendar inputs" : "Show calendar inputs") { model.showCalendarInputs.toggle() }.frame(minHeight: 44).accessibilityIdentifier("reports.calendar.toggle") }; Text("Calendar log").font(.headline); if model.showCalendarInputs { ForEach(report.days.filter { $0.calendarNote != nil || !$0.calendarLabels.isEmpty }) { day in VStack(alignment: .leading, spacing: 4) { Text(day.date).font(.subheadline.weight(.semibold)); if let note = day.calendarNote { Text(note) }; ForEach(day.calendarLabels) { label in Text("\(label.label) · \(calendarPortionText(label.portion))").font(.caption).accessibilityLabel("\(label.label), \(calendarPortionText(label.portion))") } }.frame(maxWidth: .infinity, alignment: .leading).padding(10).background(.secondary.opacity(0.08), in: RoundedRectangle(cornerRadius: 8)) } } } } } }
    private func calendarPortionText(_ portion: Decimal?) -> String { guard let portion else { return "Marked" }; return portion == 1 ? "1 day" : "\(portion) days" }
    private var breakdown: some View { VStack(alignment: .leading, spacing: 8) { HStack { Text("Breakdown").font(.headline); Spacer(); Picker("Group by", selection: $model.breakdown) { ForEach(ReportBreakdown.allCases, id: \.self) { Text($0.rawValue).tag($0) } }.labelsHidden() }; let values = model.breakdown == .path ? model.report!.paths : model.report!.sessionLabels; ForEach(Array(values.enumerated()), id: \.element.identity) { index, value in HStack { Circle().fill(WorkspaceTheme.color(value.color ?? WorkspaceTheme.palette[index % WorkspaceTheme.palette.count])).frame(width: 10, height: 10); Text(value.label).lineLimit(2); Spacer(); Text(duration(value.seconds)).monospacedDigit() }.padding(.vertical, 6) }; if values.isEmpty { Text("No tracked time in this period.").foregroundStyle(.secondary) }; let total = values.reduce(Int64(0)) { $0 + $1.seconds }; HStack { ZStack { Circle().stroke(WorkspaceTheme.border(scheme), lineWidth: 14); Circle().trim(from: 0, to: values.isEmpty ? 0 : 1).stroke(WorkspaceTheme.accent(scheme), lineWidth: 14).rotationEffect(.degrees(-90)) }.frame(width: 54, height: 54).accessibilityHidden(true); VStack(alignment: .leading) { Text("Donut summary").font(.caption.weight(.semibold)); Text(duration(total)).monospacedDigit(); Text(values.isEmpty ? "No tracked time in this period." : values.map { "\($0.label): \(duration($0.seconds))" }.joined(separator: ", ")).font(.caption).foregroundStyle(.secondary).fixedSize(horizontal: false, vertical: true) } }.accessibilityElement(children: .combine).accessibilityLabel("Breakdown total \(duration(total)). \(values.isEmpty ? "No tracked time in this period." : values.map { "\($0.label): \(duration($0.seconds))" }.joined(separator: ", "))"); Text("\(model.report?.days.filter { $0.paths.reduce(0) { $0 + $1.seconds } > 0 }.count ?? 0) active days").font(.caption).foregroundStyle(.secondary) }.padding(14).background(.secondary.opacity(0.08), in: RoundedRectangle(cornerRadius: 10)) }
}
