import { defineStore } from "pinia";
import { api } from "../lib/api";

// pathId is set on the board every path owns; only path boards can be hidden and only custom boards pinned.
export type Board = { id: string; name: string; archived: boolean; pathId?: string | null; hidden?: boolean; pinned?: boolean; createdAt: string; updatedAt: string };
export type BoardStatus = { id: string; name: string; position: number; archived: boolean };
export type BoardCard = { id: string; statusId: string; title: string; body: string; priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT"; startDate?: string; dueDate?: string; position: number; archived: boolean; pathIds: string[]; labelIds: string[]; createdAt: string; updatedAt: string };
type CardPage = { items: BoardCard[]; nextCursor: number | null };
type CardInput = Pick<BoardCard, "title" | "body" | "priority"> & { startDate?: string; dueDate?: string; pathIds?: string[]; labelIds?: string[]; expectedUpdatedAt?: string };
type NewCardInput = CardInput & { statusId?: string };

function cardOverlapsWindow(card: BoardCard, from: string, to: string) {
  const start = card.startDate || card.dueDate;
  const end = card.dueDate || card.startDate;
  return Boolean(start && end && start <= to && end >= from);
}

export const useBoardsStore = defineStore("boards", {
  state: () => ({ boards: [] as Board[], archivedBoards: [] as Board[], statuses: [] as BoardStatus[], cards: [] as BoardCard[], ganttCards: [] as BoardCard[], ganttFrom: "", ganttTo: "", ganttLoadRevision: 0, boardListRevision: 0, moveRevisions: {} as Record<string, number>, cardUpdateRevisions: {} as Record<string, number>, boardMutations: {} as Record<string, boolean>, archivedCards: [] as BoardCard[], pageCursors: {} as Record<string, number | null>, pageLoading: {} as Record<string, boolean>, pageErrors: {} as Record<string, string>, selectedId: "", loading: false, creatingBoard: false, updatingBoard: false, creatingCard: false, error: "", boardLoadRevision: 0 }),
  getters: { selected: (state) => state.boards.find((board) => board.id === state.selectedId) },
  actions: {
    reset() { this.boardLoadRevision++; this.ganttLoadRevision++; this.boardListRevision++; this.boards = []; this.archivedBoards = []; this.statuses = []; this.cards = []; this.ganttCards = []; this.ganttFrom = ""; this.ganttTo = ""; this.moveRevisions = {}; this.cardUpdateRevisions = {}; this.boardMutations = {}; this.archivedCards = []; this.pageCursors = {}; this.pageLoading = {}; this.pageErrors = {}; this.selectedId = ""; this.loading = false; this.creatingBoard = false; this.updatingBoard = false; this.creatingCard = false; this.error = ""; },
    async loadBoards(includeArchived = false) { const revision = ++this.boardListRevision; this.loading = true; this.error = ""; try { const items = await api<Board[]>(`/boards?archived=${includeArchived}`); if (revision !== this.boardListRevision) return; if (includeArchived) this.archivedBoards = items; else { this.boards = items; if (!this.selectedId || !items.some((b) => b.id === this.selectedId)) this.selectedId = items[0]?.id || ""; } } catch { if (revision === this.boardListRevision) this.error = "Unable to load boards."; } finally { if (revision === this.boardListRevision) this.loading = false; } },
    async createBoard(name: string) { if (this.creatingBoard) return null; this.creatingBoard = true; try { const board = await api<Board>("/boards", { method: "POST", body: JSON.stringify({ name }) }); this.boards.push(board); this.selectedId = board.id; await this.loadBoard(); return board; } finally { this.creatingBoard = false; } },
    async updateBoard(id: string, name: string) { if (this.updatingBoard) return null; this.updatingBoard = true; try { const board = await api<Board>(`/boards/${id}`, { method: "PUT", body: JSON.stringify({ name }) }); const current = this.boards.find((item) => item.id === id); if (current) Object.assign(current, board); const archived = this.archivedBoards.find((item) => item.id === id); if (archived) Object.assign(archived, board); return board; } finally { this.updatingBoard = false; } },
    async archiveBoard(id: string, restore = false) { if (this.boardMutations[id]) return null; this.boardMutations[id] = true; try { const board = await api<Board>(`/boards/${id}/${restore ? "restore" : "archive"}`, { method: "POST" }); const wasSelected = this.selectedId === id; const shouldSelectRestored = restore && !this.selectedId; this.boards = this.boards.filter((item) => item.id !== id); this.archivedBoards = this.archivedBoards.filter((item) => item.id !== id); if (restore) this.boards.unshift(board); if (wasSelected || shouldSelectRestored) { this.selectedId = restore ? board.id : this.boards[0]?.id || ""; this.statuses = []; this.cards = []; this.ganttCards = []; this.archivedCards = []; await this.loadBoard(); } return board; } finally { delete this.boardMutations[id]; } },
    async setVisibility(id: string, hidden: boolean) { const board = await api<Board>(`/boards/${id}/visibility`, { method: "POST", body: JSON.stringify({ hidden }) }); if (hidden) { const wasSelected = this.selectedId === id; this.boards = this.boards.filter((item) => item.id !== id); if (wasSelected) { this.selectedId = this.boards[0]?.id || ""; await this.loadBoard(); } } else if (!this.boards.some((item) => item.id === id)) await this.loadBoards(); return board; },
    async pinBoard(id: string, pinned: boolean) { const board = await api<Board>(`/boards/${id}/pin`, { method: "POST", body: JSON.stringify({ pinned }) }); await this.loadBoards(); return board; },
    // ids is the full custom-board order; path boards keep their slots.
    async reorderBoards(ids: string[]) { const previous = [...this.boards]; const byId = new Map(this.boards.map((board) => [board.id, board])); const queue = ids.map((id) => byId.get(id)).filter((board): board is Board => Boolean(board)); this.boards = this.boards.map((board) => board.pathId ? board : queue.shift() || board); try { await api(`/boards/order`, { method: "PUT", body: JSON.stringify({ ids }) }); } catch (error) { this.boards = previous; throw error; } },
    async loadBoard() { const revision = ++this.boardLoadRevision; const boardId = this.selectedId; this.ganttLoadRevision++; this.statuses = []; this.cards = []; this.archivedCards = []; this.ganttCards = []; this.ganttFrom = ""; this.ganttTo = ""; this.pageCursors = {}; this.pageLoading = {}; this.pageErrors = {}; if (!boardId) return; this.loading = true; try { const nextStatuses = await api<BoardStatus[]>(`/boards/${boardId}/statuses`); if (revision !== this.boardLoadRevision || this.selectedId !== boardId) return; const active = nextStatuses.filter((status) => !status.archived); const pages = await Promise.all(active.map((status) => api<CardPage>(`/boards/${boardId}/cards/page?statusId=${status.id}&cursor=-1&limit=20`))); if (revision !== this.boardLoadRevision || this.selectedId !== boardId) return; this.statuses = nextStatuses; this.cards = pages.flatMap((page) => page.items); this.pageCursors = Object.fromEntries(active.map((status, index) => [status.id, pages[index].nextCursor])); } catch { if (revision === this.boardLoadRevision) this.error = "Unable to load this board."; } finally { if (revision === this.boardLoadRevision) this.loading = false; } },
    async loadMore(statusId: string) { const cursor = this.pageCursors[statusId]; if (cursor === null || cursor === undefined || this.pageLoading[statusId] || this.pageErrors[statusId]) return; const boardId = this.selectedId; const revision = this.boardLoadRevision; this.pageLoading[statusId] = true; try { const page = await api<CardPage>(`/boards/${boardId}/cards/page?statusId=${statusId}&cursor=${cursor}&limit=20`); if (this.selectedId !== boardId || this.boardLoadRevision !== revision) return; this.cards = [...this.cards, ...page.items]; this.pageCursors[statusId] = page.nextCursor; delete this.pageErrors[statusId]; this.error = ""; } catch (error) { if (this.selectedId !== boardId || this.boardLoadRevision !== revision) return; this.pageErrors[statusId] = "Unable to load more cards. Try again."; this.error = this.pageErrors[statusId]; throw error; } finally { this.pageLoading[statusId] = false; } },
    async retryLoadMore(statusId: string) { delete this.pageErrors[statusId]; return this.loadMore(statusId); },
    async loadGantt(from: string, to: string) { const revision = ++this.ganttLoadRevision; const boardId = this.selectedId; if (!boardId) { this.ganttCards = []; return; } try { const items = await api<BoardCard[]>(`/boards/${boardId}/gantt?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`); if (revision !== this.ganttLoadRevision || this.selectedId !== boardId) return; this.ganttFrom = from; this.ganttTo = to; this.ganttCards = items; this.error = ""; } catch { if (revision === this.ganttLoadRevision && this.selectedId === boardId) { this.ganttCards = []; this.error = "Unable to load the timeline. Try again."; } } },
    async loadArchivedCards() { if (!this.selectedId) return; this.archivedCards = await api<BoardCard[]>(`/boards/${this.selectedId}/cards?archived=true`); },
    syncGanttCard(card: BoardCard) { const index = this.ganttCards.findIndex((item) => item.id === card.id); const visible = Boolean(this.ganttFrom && this.ganttTo && !card.archived && cardOverlapsWindow(card, this.ganttFrom, this.ganttTo)); if (!visible) { if (index >= 0) this.ganttCards.splice(index, 1); return; } if (index >= 0) this.ganttCards[index] = card; else this.ganttCards.push(card); },
    async createCard(input: NewCardInput) { if (this.creatingCard) return null; this.creatingCard = true; try { const card = await api<BoardCard>(`/boards/${this.selectedId}/cards`, { method: "POST", body: JSON.stringify(input) }); this.cards.push(card); this.syncGanttCard(card); return card; } finally { this.creatingCard = false; } },
    async updateCard(card: BoardCard, input: CardInput) { const revision = (this.cardUpdateRevisions[card.id] || 0) + 1; this.cardUpdateRevisions[card.id] = revision; const boardId = this.selectedId; const boardRevision = this.boardLoadRevision; try { const saved = await api<BoardCard>(`/boards/${boardId}/cards/${card.id}`, { method: "PUT", body: JSON.stringify({ ...input, expectedUpdatedAt: input.expectedUpdatedAt || card.updatedAt }) }); if (this.cardUpdateRevisions[card.id] !== revision || this.selectedId !== boardId || this.boardLoadRevision !== boardRevision) return card; const index = this.cards.findIndex((item) => item.id === card.id); if (index >= 0) this.cards[index] = saved; this.syncGanttCard(saved); return saved; } catch (error) { if (this.cardUpdateRevisions[card.id] !== revision || this.selectedId !== boardId || this.boardLoadRevision !== boardRevision) return card; if (typeof error === "object" && error !== null && "status" in error && (error as { status?: number }).status === 409) { try { const latest = await api<BoardCard>(`/boards/${boardId}/cards/${card.id}`); if (this.cardUpdateRevisions[card.id] === revision && this.selectedId === boardId && this.boardLoadRevision === boardRevision) { Object.assign(card, latest); this.syncGanttCard(latest); } } catch { /* Preserve the draft and original conflict when refresh also fails. */ } } throw error; } },
    async moveCard(card: BoardCard, statusId: string, position: number) { const destination = this.statuses.find((status) => status.id === statusId); if ((this.statuses.length > 0 && (!destination || destination.archived)) || !Number.isInteger(position) || position < 0) throw new Error("Invalid card destination."); const revision = (this.moveRevisions[card.id] || 0) + 1; this.moveRevisions[card.id] = revision; const sourceId = card.statusId; const sourceCards = this.cards.filter((item) => !item.archived && item.statusId === sourceId && item.id !== card.id).sort((a, b) => a.position - b.position); const destinationCards = sourceId === statusId ? sourceCards : this.cards.filter((item) => !item.archived && item.statusId === statusId && item.id !== card.id).sort((a, b) => a.position - b.position); const previous = [...new Set([card, ...sourceCards, ...destinationCards])].map((item) => ({ item, statusId: item.statusId, position: item.position })); const destinationPosition = Math.min(position, destinationCards.length); const nextDestination = [...destinationCards]; nextDestination.splice(destinationPosition, 0, card); card.statusId = statusId; sourceCards.forEach((item, index) => { item.statusId = sourceId; item.position = index; }); nextDestination.forEach((item, index) => { item.statusId = statusId; item.position = index; }); const ganttCards = this.ganttCards.filter((item) => previous.some((snapshot) => snapshot.item.id === item.id)); ganttCards.forEach((item) => { const source = this.cards.find((candidate) => candidate.id === item.id); if (source) { item.statusId = source.statusId; item.position = source.position; } }); try { const saved = await api<BoardCard>(`/boards/${this.selectedId}/cards/${card.id}/move`, { method: "POST", body: JSON.stringify({ statusId, position: destinationPosition }) }); if (this.moveRevisions[card.id] !== revision) return card; Object.assign(card, saved); const timelineCard = this.ganttCards.find((item) => item.id === card.id); if (timelineCard) Object.assign(timelineCard, saved); else this.syncGanttCard(saved); return saved; } catch (error) { if (this.moveRevisions[card.id] !== revision) return card; previous.forEach((snapshot) => { snapshot.item.statusId = snapshot.statusId; snapshot.item.position = snapshot.position; }); ganttCards.forEach((item) => { const snapshot = previous.find((value) => value.item.id === item.id); if (snapshot) { item.statusId = snapshot.statusId; item.position = snapshot.position; } }); throw error; } },
    async archiveCard(card: BoardCard, restore = false) { const saved = await api<BoardCard>(`/boards/${this.selectedId}/cards/${card.id}/${restore ? "restore" : "archive"}`, { method: "POST" }); if (restore) { this.cards = this.cards.filter((item) => item.id !== card.id); this.cards.push(saved); this.syncGanttCard(saved); } else { this.cards = this.cards.filter((item) => item.id !== card.id); this.syncGanttCard(saved); } return saved; },
    // Status actions default to the open board; board settings can pass another
    // board's id and its status list without switching the open board.
    async fetchStatuses(boardId: string) { return api<BoardStatus[]>(`/boards/${boardId}/statuses`); },
    async createStatus(name: string, targetBoardId?: string) { const boardId = targetBoardId ?? this.selectedId; const status = await api<BoardStatus>(`/boards/${boardId}/statuses`, { method: "POST", body: JSON.stringify({ name }) }); if (boardId === this.selectedId) this.statuses.push(status); return status; },
    async updateStatus(status: BoardStatus, name: string, targetBoardId?: string) { const boardId = targetBoardId ?? this.selectedId; const saved = await api<BoardStatus>(`/boards/${boardId}/statuses/${status.id}`, { method: "PUT", body: JSON.stringify({ name }) }); Object.assign(status, saved); return saved; },
    async reorderStatuses(ids: string[], targetBoardId?: string, knownStatuses?: BoardStatus[]) { const boardId = targetBoardId ?? this.selectedId; const allStatuses = knownStatuses ?? this.statuses; const activeIds = [...ids]; const normalizedIds = ids.length === allStatuses.length ? ids : allStatuses.map((status) => status.archived ? status.id : activeIds.shift()!).filter(Boolean); const saved = await api<BoardStatus[]>(`/boards/${boardId}/statuses/order`, { method: "PUT", body: JSON.stringify({ ids: normalizedIds }) }); if (boardId === this.selectedId) this.statuses = saved; return saved; },
    async archiveStatus(status: BoardStatus, restore = false, targetBoardId?: string) { const boardId = targetBoardId ?? this.selectedId; await api(`/boards/${boardId}/statuses/${status.id}/${restore ? "restore" : "archive"}`, { method: "POST" }); status.archived = !restore; if (boardId === this.selectedId) await this.loadBoard(); },
  },
});
