import { defineStore } from "pinia";
import { api } from "../lib/api";

export type Board = { id: string; name: string; archived: boolean; createdAt: string; updatedAt: string };
export type BoardStatus = { id: string; name: string; position: number; archived: boolean };
export type BoardCard = { id: string; statusId: string; title: string; body: string; priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT"; startDate?: string; dueDate?: string; position: number; archived: boolean; pathIds: string[]; labelIds: string[]; createdAt: string; updatedAt: string };
type CardPage = { items: BoardCard[]; nextCursor: number | null };
type CardInput = Pick<BoardCard, "title" | "body" | "priority"> & { startDate?: string; dueDate?: string; pathIds?: string[]; labelIds?: string[] };

function cardOverlapsWindow(card: BoardCard, from: string, to: string) {
  const start = card.startDate || card.dueDate;
  const end = card.dueDate || card.startDate;
  return Boolean(start && end && start <= to && end >= from);
}

export const useBoardsStore = defineStore("boards", {
  state: () => ({ boards: [] as Board[], archivedBoards: [] as Board[], statuses: [] as BoardStatus[], cards: [] as BoardCard[], ganttCards: [] as BoardCard[], ganttFrom: "", ganttTo: "", archivedCards: [] as BoardCard[], pageCursors: {} as Record<string, number | null>, pageLoading: {} as Record<string, boolean>, selectedId: "", loading: false, creatingBoard: false, creatingCard: false, error: "", boardLoadRevision: 0 }),
  getters: { selected: (state) => state.boards.find((board) => board.id === state.selectedId) },
  actions: {
    reset() { this.boardLoadRevision++; this.boards = []; this.archivedBoards = []; this.statuses = []; this.cards = []; this.ganttCards = []; this.ganttFrom = ""; this.ganttTo = ""; this.archivedCards = []; this.pageCursors = {}; this.pageLoading = {}; this.selectedId = ""; this.loading = false; this.creatingBoard = false; this.creatingCard = false; this.error = ""; },
    async loadBoards(includeArchived = false) { this.loading = true; this.error = ""; try { const items = await api<Board[]>(`/boards?archived=${includeArchived}`); if (includeArchived) this.archivedBoards = items; else { this.boards = items; if (!this.selectedId || !items.some((b) => b.id === this.selectedId)) this.selectedId = items[0]?.id || ""; } } catch { this.error = "Unable to load boards."; } finally { this.loading = false; } },
    async createBoard(name: string) { if (this.creatingBoard) return null; this.creatingBoard = true; try { const board = await api<Board>("/boards", { method: "POST", body: JSON.stringify({ name }) }); this.boards.unshift(board); this.selectedId = board.id; await this.loadBoard(); return board; } finally { this.creatingBoard = false; } },
    async archiveBoard(id: string, restore = false) { const board = await api<Board>(`/boards/${id}/${restore ? "restore" : "archive"}`, { method: "POST" }); this.boards = this.boards.filter((item) => item.id !== id); this.archivedBoards = this.archivedBoards.filter((item) => item.id !== id); if (restore) this.boards.unshift(board); if (this.selectedId === id) this.selectedId = this.boards[0]?.id || ""; return board; },
    async loadBoard() { const revision = ++this.boardLoadRevision; const boardId = this.selectedId; this.ganttCards = []; this.ganttFrom = ""; this.ganttTo = ""; if (!boardId) { this.statuses = []; this.cards = []; return; } this.loading = true; try { const nextStatuses = await api<BoardStatus[]>(`/boards/${boardId}/statuses`); if (revision !== this.boardLoadRevision || this.selectedId !== boardId) return; const active = nextStatuses.filter((status) => !status.archived); const pages = await Promise.all(active.map((status) => api<CardPage>(`/boards/${boardId}/cards/page?statusId=${status.id}&cursor=-1&limit=20`))); if (revision !== this.boardLoadRevision || this.selectedId !== boardId) return; this.statuses = nextStatuses; this.cards = pages.flatMap((page) => page.items); this.pageCursors = Object.fromEntries(active.map((status, index) => [status.id, pages[index].nextCursor])); } catch { if (revision === this.boardLoadRevision) this.error = "Unable to load this board."; } finally { if (revision === this.boardLoadRevision) this.loading = false; } },
    async loadMore(statusId: string) { const cursor = this.pageCursors[statusId]; if (cursor === null || cursor === undefined || this.pageLoading[statusId]) return; this.pageLoading[statusId] = true; try { const page = await api<CardPage>(`/boards/${this.selectedId}/cards/page?statusId=${statusId}&cursor=${cursor}&limit=20`); this.cards = [...this.cards, ...page.items]; this.pageCursors[statusId] = page.nextCursor; this.error = ""; } catch (error) { this.error = "Unable to load more cards. Try again."; throw error; } finally { this.pageLoading[statusId] = false; } },
    async loadGantt(from: string, to: string) { if (!this.selectedId) { this.ganttCards = []; return; } const items = await api<BoardCard[]>(`/boards/${this.selectedId}/gantt?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`); this.ganttFrom = from; this.ganttTo = to; this.ganttCards = items; },
    async loadArchivedCards() { if (!this.selectedId) return; this.archivedCards = await api<BoardCard[]>(`/boards/${this.selectedId}/cards?archived=true`); },
    syncGanttCard(card: BoardCard) { const index = this.ganttCards.findIndex((item) => item.id === card.id); const visible = Boolean(this.ganttFrom && this.ganttTo && !card.archived && cardOverlapsWindow(card, this.ganttFrom, this.ganttTo)); if (!visible) { if (index >= 0) this.ganttCards.splice(index, 1); return; } if (index >= 0) this.ganttCards[index] = card; else this.ganttCards.push(card); },
    async createCard(input: CardInput) { if (this.creatingCard) return null; this.creatingCard = true; try { const card = await api<BoardCard>(`/boards/${this.selectedId}/cards`, { method: "POST", body: JSON.stringify(input) }); this.cards.push(card); this.syncGanttCard(card); return card; } finally { this.creatingCard = false; } },
    async updateCard(card: BoardCard, input: CardInput) { const saved = await api<BoardCard>(`/boards/${this.selectedId}/cards/${card.id}`, { method: "PUT", body: JSON.stringify(input) }); const index = this.cards.findIndex((item) => item.id === card.id); if (index >= 0) this.cards[index] = saved; this.syncGanttCard(saved); return saved; },
    async moveCard(card: BoardCard, statusId: string, position: number) { const previous = { statusId: card.statusId, position: card.position }; const ganttCard = this.ganttCards.find((item) => item.id === card.id); const previousGantt = ganttCard && { statusId: ganttCard.statusId, position: ganttCard.position }; card.statusId = statusId; card.position = position; if (ganttCard) { ganttCard.statusId = statusId; ganttCard.position = position; } try { const saved = await api<BoardCard>(`/boards/${this.selectedId}/cards/${card.id}/move`, { method: "POST", body: JSON.stringify({ statusId, position }) }); Object.assign(card, saved); if (ganttCard) Object.assign(ganttCard, saved); } catch (error) { Object.assign(card, previous); if (ganttCard && previousGantt) Object.assign(ganttCard, previousGantt); throw error; } },
    async archiveCard(card: BoardCard, restore = false) { const saved = await api<BoardCard>(`/boards/${this.selectedId}/cards/${card.id}/${restore ? "restore" : "archive"}`, { method: "POST" }); if (restore) { this.cards = this.cards.filter((item) => item.id !== card.id); this.cards.push(saved); this.syncGanttCard(saved); } else { this.cards = this.cards.filter((item) => item.id !== card.id); this.syncGanttCard(saved); } return saved; },
    async createStatus(name: string) { const status = await api<BoardStatus>(`/boards/${this.selectedId}/statuses`, { method: "POST", body: JSON.stringify({ name }) }); this.statuses.push(status); return status; },
    async updateStatus(status: BoardStatus, name: string) { const saved = await api<BoardStatus>(`/boards/${this.selectedId}/statuses/${status.id}`, { method: "PUT", body: JSON.stringify({ name }) }); Object.assign(status, saved); return saved; },
    async reorderStatuses(ids: string[]) { const saved = await api<BoardStatus[]>(`/boards/${this.selectedId}/statuses/order`, { method: "PUT", body: JSON.stringify({ ids }) }); this.statuses = saved; return saved; },
    async archiveStatus(status: BoardStatus, restore = false) { await api(`/boards/${this.selectedId}/statuses/${status.id}/${restore ? "restore" : "archive"}`, { method: "POST" }); status.archived = !restore; await this.loadBoard(); },
  },
});
