<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, shallowRef, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import { storeToRefs } from "pinia";
import { EditorContent } from "@tiptap/vue-3";
import { Editor } from "@tiptap/core";
import StarterKit from "@tiptap/starter-kit";
import { useBoardsStore, type BoardCard, type BoardStatus } from "../stores/boards";
import { usePathsStore } from "../stores/paths";
import { useLabelsStore } from "../stores/labels";
import { addCalendarDays, barPosition, timelineDays } from "../lib/board-gantt";
import { ApiError } from "../lib/api";

const store = useBoardsStore();
const pathsStore = usePathsStore();
const labelsStore = useLabelsStore();
const { boards, statuses, cards, ganttCards, loading } = storeToRefs(store);
const route = useRoute(); const router = useRouter();
const view = computed(() => route.query.view === "gantt" ? "gantt" : "kanban");
const showArchived = ref(false), archiveConfirmOpen = ref(false), archiveCardConfirm = ref<BoardCard | null>(null), newBoardInput = ref<HTMLInputElement | null>(null), newBoard = ref(""), newCardTitle = ref(""), newStatus = ref(""), editingBoard = ref(false), boardDraft = ref(""), error = ref("");
function dismissError() { error.value = ""; store.error = ""; }
const editing = ref<BoardCard | null>(null), lastFocusedCardId = ref(""), lastFocusedCard = shallowRef<HTMLElement | null>(null), discardOpen = ref(false), savingCard = ref(false), cardDateError = ref(""), originalDraft = ref(""), draft = ref({ title: "", body: "{}", priority: "MEDIUM" as BoardCard["priority"], startDate: "", dueDate: "", pathIds: [] as string[], labelIds: [] as string[] });
const cardEditor = shallowRef<Editor | null>(null);
const editingStatusId = ref(""), statusDraft = ref(""), showArchivedCards = ref(false), showArchivedStatuses = ref(false);
const pageObservers = new Map<string, IntersectionObserver>();
const today = new Date().toISOString().slice(0, 10);
const ganttFrom = ref(typeof route.query.from === "string" ? route.query.from : today);
const ganttTo = ref(typeof route.query.to === "string" ? route.query.to : addCalendarDays(ganttFrom.value, 13));
const visibleDays = computed(() => timelineDays(ganttFrom.value, ganttTo.value));
const timelineWidth = computed(() => Math.max(100, visibleDays.value.length * 56));
const isWeekend = (value: string) => [0, 6].includes(new Date(`${value}T00:00:00Z`).getUTCDay());
const activeStatuses = computed(() => statuses.value.filter((status) => !status.archived));
const archivedStatuses = computed(() => statuses.value.filter((status) => status.archived));
const cardsFor = (statusId: string) => cards.value.filter((card) => card.statusId === statusId && !card.archived).sort((a, b) => a.position - b.position);
const statusName = (statusId: string) => statuses.value.find((status) => status.id === statusId)?.name || "Status";
const cardAccent = (card: BoardCard) => pathsStore.activePaths.find((path) => card.pathIds.includes(path.id))?.color || undefined;
const barStyle = (card: BoardCard) => { const position = barPosition(card.startDate || card.dueDate, card.dueDate || card.startDate, visibleDays.value); return position ? { left: `${position.left}%`, width: `${position.width}%` } : {}; };
function selectBoard(id: string) { store.selectedId = id; void router.replace({ query: { ...route.query, board: id } }); void store.loadBoard(); }
function beginBoardRename() { const board = store.selected; if (!board) return; boardDraft.value = board.name; editingBoard.value = true; }
async function saveBoardRename() { if (!store.selectedId || !boardDraft.value.trim() || store.updatingBoard) return; try { await store.updateBoard(store.selectedId, boardDraft.value); editingBoard.value = false; } catch { error.value = "Could not rename board."; } }
function setView(next: string) { if (view.value === next) return; void router.push({ query: { ...route.query, view: next, ...(next === "gantt" ? { from: ganttFrom.value, to: ganttTo.value } : {}) } }); }
function updateGanttRange() { if (!ganttFrom.value || !ganttTo.value || ganttTo.value < ganttFrom.value) { error.value = "Choose a valid inclusive date range."; return; } error.value = ""; void router.replace({ query: { ...route.query, view: "gantt", from: ganttFrom.value, to: ganttTo.value } }); void store.loadGantt(ganttFrom.value, ganttTo.value); }
function shiftGantt(amount: number) { ganttFrom.value = addCalendarDays(ganttFrom.value, amount); ganttTo.value = addCalendarDays(ganttTo.value, amount); updateGanttRange(); }
async function createBoard() { if (!newBoard.value.trim()) return; try { await store.createBoard(newBoard.value); newBoard.value = ""; await router.replace({ query: { ...route.query, board: store.selectedId } }); } catch { error.value = "Could not create board."; } }
async function createCard() { if (!store.selectedId) return; try { await store.createCard({ title: newCardTitle.value, body: "{}", priority: "MEDIUM" }); newCardTitle.value = ""; } catch { error.value = "Could not create card."; } }
function defaultBoardDocument() { return { type: "doc", content: [{ type: "paragraph" }] }; }
function parseBoardBody(body: string) { try { const parsed = JSON.parse(body); return parsed?.type === "doc" ? parsed : defaultBoardDocument(); } catch { return defaultBoardDocument(); } }
function destroyCardEditor() { cardEditor.value?.destroy(); cardEditor.value = null; }
function rememberCardFocus(event: PointerEvent) { const card = (event.target as HTMLElement | null)?.closest<HTMLElement>(".board-card"); if (card) lastFocusedCard.value = card; }
function restoreCardFocus() { const cardId = lastFocusedCardId.value; if (cardId) void nextTick(() => (lastFocusedCard.value || document.getElementById(`board-card-${cardId}`))?.focus()); }
function warnBeforeUnload(event: BeforeUnloadEvent) { if (editing.value && JSON.stringify(draft.value) !== originalDraft.value) { event.preventDefault(); event.returnValue = ""; } }
function editCard(card: BoardCard) { destroyCardEditor(); lastFocusedCardId.value = card.id; editing.value = card; cardDateError.value = ""; draft.value = { title: card.title, body: card.body, priority: card.priority, startDate: card.startDate || "", dueDate: card.dueDate || "", pathIds: [...card.pathIds], labelIds: [...card.labelIds] }; originalDraft.value = JSON.stringify(draft.value); discardOpen.value = false; cardEditor.value = new Editor({ extensions: [StarterKit], content: parseBoardBody(card.body), editorProps: { attributes: { role: "textbox", "aria-label": "Card body", "aria-multiline": "true" } }, onUpdate: ({ editor }) => { draft.value.body = JSON.stringify(editor.getJSON()); } }); }
function requestCloseEditor() { if (editing.value && JSON.stringify(draft.value) !== originalDraft.value) discardOpen.value = true; else { destroyCardEditor(); editing.value = null; restoreCardFocus(); } }
function discardChanges() { discardOpen.value = false; destroyCardEditor(); editing.value = null; cardDateError.value = ""; restoreCardFocus(); }
async function saveCard() { if (!editing.value || savingCard.value) return; if (draft.value.startDate && draft.value.dueDate && draft.value.dueDate < draft.value.startDate) { cardDateError.value = "Due date must be on or after the start date."; return; } cardDateError.value = ""; savingCard.value = true; try { await store.updateCard(editing.value, { ...draft.value, startDate: draft.value.startDate || undefined, dueDate: draft.value.dueDate || undefined }); destroyCardEditor(); editing.value = null; discardOpen.value = false; restoreCardFocus(); } catch (saveError) { error.value = saveError instanceof ApiError && saveError.status === 408 ? "The request timed out. Try again." : saveError instanceof ApiError && saveError.status === 409 ? "This card changed elsewhere. Try saving again." : "Could not save card."; } finally { savingCard.value = false; } }
async function addStatus() { if (!newStatus.value.trim()) return; try { await store.createStatus(newStatus.value); newStatus.value = ""; } catch { error.value = "Could not create status."; } }
async function restoreStatus(status: BoardStatus) { try { await store.archiveStatus(status, true); } catch { error.value = "Could not restore status."; } }
function editStatus(status: BoardStatus) { editingStatusId.value = status.id; statusDraft.value = status.name; }
async function saveStatus(status: BoardStatus) { if (!statusDraft.value.trim()) return; try { await store.updateStatus(status, statusDraft.value); editingStatusId.value = ""; } catch { error.value = "Could not save status."; } }
async function moveStatus(status: BoardStatus, direction: number) { const index = activeStatuses.value.findIndex((item) => item.id === status.id); const target = activeStatuses.value[index + direction]; if (!target) return; try { await store.reorderStatuses(activeStatuses.value.map((item) => item.id).map((id, itemIndex, ids) => ids[itemIndex] === status.id ? ids[itemIndex + direction] : ids[itemIndex] === target.id ? status.id : id)); } catch { error.value = "Could not reorder status."; } }
async function moveCard(card: BoardCard, direction: number) { const currentIndex = activeStatuses.value.findIndex((status) => status.id === card.statusId); const next = activeStatuses.value[currentIndex + direction]; if (!next) return; try { await store.moveCard(card, next.id, cardsFor(next.id).length); } catch { error.value = "Could not move card. The change was rolled back."; } }
async function reorderCard(card: BoardCard, direction: number) { const column = cardsFor(card.statusId); const index = column.findIndex((item) => item.id === card.id); const target = index + direction; if (index < 0 || target < 0 || target >= column.length) return; try { await store.moveCard(card, card.statusId, target); } catch { error.value = "Could not reorder card. The change was rolled back."; } }
function moveFocusedCard(event: KeyboardEvent) { if (!event.altKey || !["ArrowUp", "ArrowDown"].includes(event.key)) return; const focused = document.activeElement?.closest<HTMLElement>(".board-card"); if (!focused) return; const elements = [...document.querySelectorAll<HTMLElement>(".board-card")]; const index = elements.indexOf(focused); const visible = activeStatuses.value.flatMap((status) => cardsFor(status.id)); const card = visible[index]; if (!card) return; event.preventDefault(); void reorderCard(card, event.key === "ArrowUp" ? -1 : 1); }
async function restoreArchivedCard(card: BoardCard) { try { await store.archiveCard(card, true); await store.loadBoard(); } catch { error.value = "Could not restore card."; } }
function observeSentinel(statusId: string, element: Element | null) { pageObservers.get(statusId)?.disconnect(); if (!element || typeof IntersectionObserver === "undefined" || store.pageCursors[statusId] === null) return; const observer = new IntersectionObserver((entries) => { if (entries.some((entry) => entry.isIntersecting)) void store.loadMore(statusId).catch(() => undefined); }); observer.observe(element); pageObservers.set(statusId, observer); }
function requestArchiveCurrent() { if (store.selectedId) archiveConfirmOpen.value = true; }
function focusNewBoard() { newBoardInput.value?.focus(); }
function requestArchiveCard(card: BoardCard) { archiveCardConfirm.value = card; }
async function confirmArchiveCard() { const card = archiveCardConfirm.value; archiveCardConfirm.value = null; if (!card) return; try { await store.archiveCard(card); } catch { error.value = "Could not archive card."; } }
async function archiveCurrent() { if (!store.selectedId) return; archiveConfirmOpen.value = false; try { await store.archiveBoard(store.selectedId); await router.replace({ query: {} }); } catch { error.value = "Could not archive board."; } }
async function toggleArchived() { showArchived.value = !showArchived.value; if (showArchived.value) await store.loadBoards(true); }
async function restoreBoard(id: string) { await store.archiveBoard(id, true); await store.loadBoards(true); }
onMounted(async () => { document.addEventListener("pointerdown", rememberCardFocus); document.addEventListener("keydown", moveFocusedCard); window.addEventListener("beforeunload", warnBeforeUnload); await Promise.all([store.loadBoards(), pathsStore.load(), labelsStore.loadScope("BOARD")]); const requested = typeof route.query.board === "string" ? route.query.board : ""; if (requested && boards.value.some((board) => board.id === requested)) store.selectedId = requested; await store.loadBoard(); if (view.value === "gantt") await store.loadGantt(ganttFrom.value, ganttTo.value); });
watch(() => store.selectedId, (id) => { if (id && route.query.board !== id) void router.replace({ query: { ...route.query, board: id } }); if (id && view.value === "gantt") void store.loadGantt(ganttFrom.value, ganttTo.value); });
watch(view, (next) => { if (next === "gantt") void store.loadGantt(ganttFrom.value, ganttTo.value); });
onBeforeUnmount(() => { document.removeEventListener("pointerdown", rememberCardFocus); document.removeEventListener("keydown", moveFocusedCard); window.removeEventListener("beforeunload", warnBeforeUnload); pageObservers.forEach((observer) => observer.disconnect()); destroyCardEditor(); });
</script>

<template>
  <section class="board-page" aria-labelledby="board-heading">
    <header class="board-header">
      <div><p class="eyebrow">Workspace</p><h1 id="board-heading">Boards</h1></div>
      <div class="board-actions"><button class="secondary" type="button" aria-label="Add board" title="Add board" @click="focusNewBoard">＋</button><button class="secondary" type="button" @click="toggleArchived">{{ showArchived ? "Active boards" : "Archived boards" }}</button><button v-if="store.selectedId" class="secondary" type="button" @click="requestArchiveCurrent">Archive board</button><button v-if="store.selectedId && !editingBoard" class="secondary" type="button" @click="beginBoardRename">Rename board</button></div>
    </header>
    <div v-if="archiveConfirmOpen" class="dialog-backdrop" role="presentation"><div class="confirm-dialog" role="alertdialog" aria-labelledby="archive-board-title" aria-describedby="archive-board-description"><h2 id="archive-board-title">Archive board?</h2><p id="archive-board-description">Cards and statuses stay retained and can be restored later.</p><div class="editor-actions"><button class="secondary" type="button" @click="archiveConfirmOpen = false">Cancel</button><button type="button" @click="archiveCurrent">Archive</button></div></div></div>
    <div v-if="archiveCardConfirm" class="dialog-backdrop" role="presentation"><div class="confirm-dialog" role="alertdialog" aria-labelledby="archive-card-title" aria-describedby="archive-card-description"><h2 id="archive-card-title">Archive card?</h2><p id="archive-card-description">{{ archiveCardConfirm.title || "Untitled card" }} will remain retained and can be restored later.</p><div class="editor-actions"><button class="secondary" type="button" @click="archiveCardConfirm = null">Cancel</button><button type="button" @click="confirmArchiveCard">Archive</button></div></div></div>
    <p v-if="error || store.error" class="board-error" role="alert">{{ error || store.error }}<button type="button" class="error-dismiss" aria-label="Dismiss board error" @click="dismissError">×</button></p>
    <div class="board-toolbar">
      <label class="board-select-label" for="board-select">Current board</label>
      <select id="board-select" :value="store.selectedId" @change="selectBoard(($event.target as HTMLSelectElement).value)"><option value="" disabled>Select a board…</option><option v-for="board in boards" :key="board.id" :value="board.id">{{ board.name }}</option></select>
      <div class="view-switch" role="group" aria-label="Board view"><button :class="{ selected: view === 'kanban' }" type="button" @click="setView('kanban')">Kanban</button><button :class="{ selected: view === 'gantt' }" type="button" @click="setView('gantt')">Gantt</button></div>
    </div>
    <form v-if="editingBoard" class="board-rename" @submit.prevent="saveBoardRename"><label>Board name<input v-model="boardDraft" name="boardName" aria-label="Board name" maxlength="120" /></label><button type="submit" :disabled="store.updatingBoard">{{ store.updatingBoard ? "Saving…" : "Save board" }}</button><button class="secondary" type="button" @click="editingBoard = false">Cancel</button></form>
    <form class="create-board" @submit.prevent="createBoard"><input ref="newBoardInput" v-model="newBoard" aria-label="New board name" name="boardName" placeholder="New board name…" maxlength="120" /><button type="submit" :disabled="store.creatingBoard">{{ store.creatingBoard ? "Creating…" : "Create board" }}</button></form>
    <div v-if="showArchived" class="archived-list"><p class="muted">Archived boards</p><p v-if="!store.archivedBoards.length">No archived boards.</p><div v-for="board in store.archivedBoards" :key="board.id" class="gantt-row"><strong>{{ board.name }}</strong><button type="button" @click="restoreBoard(board.id)">Restore</button></div></div>
    <div v-if="loading" class="board-empty" aria-live="polite">Loading board…</div>
    <div v-else-if="!store.selectedId" class="board-empty"><h2>Create your first board</h2><p>Keep projects, priorities, and dates together in one focused workspace.</p></div>
    <template v-else-if="view === 'kanban'">
      <form class="create-card" @submit.prevent="createCard"><input v-model="newCardTitle" aria-label="New card title" name="cardTitle" placeholder="Add a card…" /><button type="submit" :disabled="store.creatingCard">{{ store.creatingCard ? "Adding…" : "Add card" }}</button></form>
      <div class="status-create"><input v-model="newStatus" aria-label="New status name" placeholder="New status…" /><button type="button" @click="addStatus">Add status</button><button v-if="archivedStatuses.length" class="secondary" type="button" @click="showArchivedStatuses = !showArchivedStatuses">{{ showArchivedStatuses ? "Hide archived statuses" : "Show archived statuses" }}</button></div><div v-if="showArchivedStatuses" class="archived-list"><p class="muted">Archived statuses</p><div v-for="status in archivedStatuses" :key="status.id" class="gantt-row"><strong>{{ status.name }}</strong><button type="button" :aria-label="`Restore ${status.name} status`" @click="restoreStatus(status)">Restore</button></div></div>
      <div class="kanban" tabindex="0" aria-label="Kanban board">
        <section v-for="status in activeStatuses" :key="status.id" class="kanban-column" :aria-labelledby="`status-${status.id}`" @dragover.prevent @drop="($event) => { const id = ($event as DragEvent).dataTransfer?.getData('text/plain'); const card = cards.find((item) => item.id === id); if (card) void store.moveCard(card, status.id, cardsFor(status.id).length); }"><header><div v-if="editingStatusId === status.id" class="status-edit"><input v-model="statusDraft" :aria-label="`Rename ${status.name}`" @keydown.enter.prevent="saveStatus(status)" /><button type="button" @click="saveStatus(status)">Save</button></div><h2 v-else :id="`status-${status.id}`">{{ status.name }}</h2><div class="column-tools"><span>{{ cardsFor(status.id).length }}</span><button type="button" :aria-label="`Move ${status.name} earlier`" :disabled="activeStatuses.indexOf(status) === 0" @click="moveStatus(status, -1)">↑</button><button type="button" :aria-label="`Move ${status.name} later`" :disabled="activeStatuses.indexOf(status) === activeStatuses.length - 1" @click="moveStatus(status, 1)">↓</button><button type="button" :aria-label="`Rename ${status.name}`" @click="editStatus(status)">Rename</button><button type="button" :aria-label="`Archive ${status.name}`" @click="store.archiveStatus(status)">Archive</button></div></header><article v-for="card in cardsFor(status.id)" :key="card.id" class="board-card" :style="{ borderInlineStartColor: cardAccent(card) }" draggable="true" tabindex="0" @dragstart="($event) => ($event as DragEvent).dataTransfer?.setData('text/plain', card.id)" @click="editCard(card)" @keydown.enter="editCard(card)"><div class="priority" :class="card.priority.toLowerCase()">{{ card.priority }}</div><h3>{{ card.title || "Untitled card" }}</h3><p v-if="card.startDate || card.dueDate">{{ card.startDate || "Any date" }} → {{ card.dueDate || "Open" }}</p><div class="card-actions"><button type="button" aria-label="Move card to previous status" @click.stop="moveCard(card, -1)">←</button><button type="button" aria-label="Move card to next status" @click.stop="moveCard(card, 1)">→</button><button type="button" class="card-archive" :aria-label="`Archive ${card.title || 'untitled card'}`" @click.stop="requestArchiveCard(card)">Archive</button></div></article><div v-if="store.pageCursors[status.id] !== null" :ref="(element) => observeSentinel(status.id, element as Element | null)" class="load-more-sentinel" aria-hidden="true"></div><button v-if="store.pageErrors[status.id]" type="button" class="secondary page-retry" aria-label="Retry loading cards" @click="store.retryLoadMore(status.id).catch(() => undefined)">Retry loading cards</button><p v-if="!cardsFor(status.id).length" class="column-empty">No cards yet</p></section>
      </div>
      <button class="secondary archive-toggle" type="button" @click="showArchivedCards = !showArchivedCards; showArchivedCards && store.loadArchivedCards()">{{ showArchivedCards ? "Hide archived cards" : "Show archived cards" }}</button><div v-if="showArchivedCards" class="archived-list"><p class="muted">Archived cards</p><p v-if="!store.archivedCards.length">No archived cards.</p><div v-for="card in store.archivedCards" :key="card.id" class="gantt-row"><strong>{{ card.title || "Untitled card" }}</strong><button type="button" @click="restoreArchivedCard(card)">Restore</button></div></div>
    </template>
    <section v-else class="gantt" aria-labelledby="gantt-heading">
      <div class="gantt-heading"><div><h2 id="gantt-heading">Timeline</h2><p class="muted">The timeline uses the same active cards as Kanban. Date ranges are inclusive.</p></div><div class="gantt-controls"><button class="secondary" type="button" aria-label="Previous timeline window" @click="shiftGantt(-visibleDays.length)">←</button><label>From<input v-model="ganttFrom" type="date" aria-label="Timeline start date" @change="updateGanttRange" /></label><label>To<input v-model="ganttTo" type="date" aria-label="Timeline end date" @change="updateGanttRange" /></label><button class="secondary" type="button" aria-label="Next timeline window" @click="shiftGantt(visibleDays.length)">→</button></div></div>
      <div class="timeline-scroll" tabindex="0" aria-label="Board card timeline"><div class="timeline" :style="{ minWidth: `${timelineWidth}px` }"><div class="timeline-header"><span class="timeline-label">Card</span><div class="timeline-days" :style="{ gridTemplateColumns: `repeat(${visibleDays.length}, minmax(56px, 1fr))` }"><span v-for="day in visibleDays" :key="day">{{ day.slice(5) }}</span></div></div><div v-for="card in ganttCards" :key="card.id" class="timeline-row"><div class="timeline-label"><strong>{{ card.title || "Untitled card" }}</strong><small>{{ statusName(card.statusId) }}</small></div><div class="timeline-track"><span v-for="day in visibleDays" :key="day" class="timeline-cell" :class="{ weekend: isWeekend(day) }"></span><button class="timeline-bar" :style="barStyle(card)" type="button" @click="editCard(card)">{{ card.title || "Untitled card" }}</button></div></div><p v-if="!ganttCards.length" class="board-empty">No dated active cards overlap this timeline window. Cards without dates stay in Kanban.</p></div></div>
    </section>
    <div v-if="editing" class="dialog-backdrop" role="presentation" @click.self="requestCloseEditor"><form class="card-editor" aria-labelledby="editor-title" @submit.prevent="saveCard"><h2 id="editor-title">Edit card</h2><label>Title<input v-model="draft.title" name="title" /></label><div class="card-body-editor"><span class="field-label">Body</span><EditorContent v-if="cardEditor" :editor="cardEditor" /></div><label>Priority<select v-model="draft.priority" name="priority"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>URGENT</option></select></label><div class="date-fields"><label>Start date<input v-model="draft.startDate" type="date" name="startDate" /></label><label>Due date<input v-model="draft.dueDate" type="date" name="dueDate" /></label></div><p v-if="cardDateError" role="alert" aria-label="Date range error">{{ cardDateError }}</p><fieldset><legend>Paths</legend><label v-for="path in pathsStore.activePaths" :key="path.id" class="check-row"><input v-model="draft.pathIds" type="checkbox" name="cardPaths" :value="path.id" />{{ path.name }}</label><button v-if="draft.pathIds.length" class="secondary clear-path" type="button" @click="draft.pathIds = []">Clear paths</button><p v-if="!pathsStore.activePaths.length" class="muted">No active paths.</p></fieldset><fieldset><legend>Board labels</legend><label v-for="label in labelsStore.forScope('BOARD')" :key="label.id" class="check-row"><input v-model="draft.labelIds" type="checkbox" :value="label.id" />{{ label.name }}</label><p v-if="!labelsStore.forScope('BOARD').length" class="muted">No BOARD labels.</p></fieldset><div class="editor-actions"><button class="secondary" type="button" @click="requestCloseEditor">Cancel</button><button type="submit" :disabled="savingCard">{{ savingCard ? "Saving…" : "Save card" }}</button></div></form><div v-if="discardOpen" class="confirm-dialog" role="alertdialog" aria-labelledby="discard-title"><h2 id="discard-title">Discard unsaved changes?</h2><p>Your card edits have not been saved.</p><div class="editor-actions"><button class="secondary" type="button" @click="discardOpen = false">Keep editing</button><button type="button" @click="discardChanges">Discard changes</button></div></div></div>
  </section>
</template>

<style scoped src="./board.css"></style>
