<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, shallowRef, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import { storeToRefs } from "pinia";
import { EditorContent } from "@tiptap/vue-3";
import { Editor } from "@tiptap/core";
import { RICH_TEXT_CLASS, richTextEditorProps, richTextExtensions } from "../lib/rich-text";
import { byPriorityThenPosition } from "../lib/board-priority";
import { useBoardsStore, type Board, type BoardCard, type BoardStatus } from "../stores/boards";
import { usePathsStore } from "../stores/paths";
import { useLabelsStore } from "../stores/labels";
import { addCalendarDays, barPosition, timelineDays } from "../lib/board-gantt";
import { ApiError } from "../lib/api";
import { vDialogFocus } from "../lib/dialog-focus";
import { VueDatePicker } from "@vuepic/vue-datepicker";
import "@vuepic/vue-datepicker/dist/main.css";
import { format, parseISO } from "date-fns";
import { theme } from "../lib/theme";
import { mdiArchiveOutline, mdiArrowCollapseHorizontal, mdiArrowExpandHorizontal, mdiArrowLeft, mdiClose, mdiDragVertical, mdiCogOutline, mdiPin, mdiPinOutline, mdiPlus, mdiSort, mdiSortDescending, mdiTrashCanOutline } from "@mdi/js";

const store = useBoardsStore();
const pathsStore = usePathsStore();
const labelsStore = useLabelsStore();
const { boards, statuses, cards, ganttCards, loading } = storeToRefs(store);
const route = useRoute(); const router = useRouter();
const view = computed(() => route.query.view === "gantt" ? "gantt" : "kanban");
const archiveConfirmOpen = ref(false), archiveCardConfirm = ref<BoardCard | null>(null), archiveStatusConfirm = ref<BoardStatus | null>(null), archivingStatusId = ref(""), newBoardOpen = ref(false), newBoardError = ref(""), newBoard = ref(""), newStatus = ref(""), error = ref("");
function dismissError() { error.value = ""; store.error = ""; }
const editing = ref<BoardCard | null>(null), lastFocusedCardId = ref(""), lastFocusedCard = shallowRef<HTMLElement | null>(null), saveState = ref<"" | "saving" | "saved" | "error">(""), saveError = ref(""), cardDateError = ref(""), savedSnapshot = ref(""), closeAnyway = ref(false), draft = ref({ title: "", body: "{}", priority: "MEDIUM" as BoardCard["priority"], startDate: "", dueDate: "", pathIds: [] as string[], labelIds: [] as string[] });
const cardEditor = shallowRef<Editor | null>(null);
// Card edits save themselves: changes are debounced into a serial queue so
// each save carries the updatedAt returned by the previous one.
const AUTOSAVE_DELAY_MS = 600;
let saveTimer: ReturnType<typeof setTimeout> | undefined;
let saveChain: Promise<void> = Promise.resolve();
// A path board's cards all belong to its path, so the path picker is hidden and the path colour is the accent.
const selectedBoard = computed(() => boards.value.find((board) => board.id === store.selectedId));
const pathColor = (pathId?: string | null) => (pathId && pathsStore.byId(pathId)?.color) || undefined;
const draftAccent = computed(() => selectedBoard.value?.pathId ? undefined : pathsStore.activePaths.find((path) => draft.value.pathIds.includes(path.id))?.color || undefined);
const draftDates = computed(() => draft.value.startDate ? [parseISO(draft.value.startDate), ...(draft.value.dueDate ? [parseISO(draft.value.dueDate)] : [])] : null);
const shortDate = (value: Date) => format(value, value.getFullYear() === new Date().getFullYear() ? "d MMM" : "d MMM yyyy");
const dateFormats = { input: (value: Date[] | null) => value?.length ? `${shortDate(value[0])}${value[1] ? ` – ${shortDate(value[1])}` : ""}` : "" };
const settingsOpen = ref(false), settingsName = ref(""), settingsBoardId = ref(""), otherBoardStatuses = ref<BoardStatus[]>([]);
// Settings can edit any board without opening it: the open board uses the
// store's statuses, any other board a list fetched for the dialog.
const settingsBoard = computed(() => boards.value.find((board) => board.id === settingsBoardId.value));
const settingsForOpenBoard = computed(() => settingsBoardId.value === store.selectedId);
const settingsAllStatuses = computed(() => settingsForOpenBoard.value ? statuses.value : otherBoardStatuses.value);
const settingsActiveStatuses = computed(() => settingsAllStatuses.value.filter((status) => !status.archived));
const statusDragId = ref(""), statusDragOrder = ref<string[] | null>(null), settingsStatusList = ref<HTMLElement | null>(null);
// While a status is dragged the dialog previews the new order; it is saved on release.
const settingsStatuses = computed(() => statusDragOrder.value ? statusDragOrder.value.map((id) => settingsActiveStatuses.value.find((status) => status.id === id)).filter((status): status is BoardStatus => Boolean(status)) : settingsActiveStatuses.value);
const pageObservers = new Map<string, IntersectionObserver>();
// The Kanban can break out of the page's max width. The preference is a
// per-browser convenience, and the viewport width is measured so the
// breakout never adds a horizontal scrollbar.
const KANBAN_WIDE_KEY = "board.kanbanWide";
const kanbanWide = ref(readKanbanWide()), viewportWidth = ref(0), contentLeft = ref(0), boardPage = ref<HTMLElement | null>(null);
function readKanbanWide() { try { return localStorage.getItem(KANBAN_WIDE_KEY) === "1"; } catch { return false; } }
function toggleKanbanWide() { measureViewport(); kanbanWide.value = !kanbanWide.value; try { localStorage.setItem(KANBAN_WIDE_KEY, kanbanWide.value ? "1" : "0"); } catch { /* Storage is optional. */ } }
function measureViewport() { viewportWidth.value = document.documentElement.clientWidth; const page = boardPage.value; if (page) contentLeft.value = page.getBoundingClientRect().left + parseFloat(getComputedStyle(page).paddingLeft || "0"); }
const today = new Date().toISOString().slice(0, 10);
const ganttFrom = ref(typeof route.query.from === "string" ? route.query.from : today);
const ganttTo = ref(typeof route.query.to === "string" ? route.query.to : addCalendarDays(ganttFrom.value, 13));
const visibleDays = computed(() => timelineDays(ganttFrom.value, ganttTo.value));
const timelineWidth = computed(() => Math.max(100, visibleDays.value.length * 56));
const isWeekend = (value: string) => [0, 6].includes(new Date(`${value}T00:00:00Z`).getUTCDay());
const activeStatuses = computed(() => statuses.value.filter((status) => !status.archived));
const sortedByPriority = (statusId: string) => store.statuses.find((status) => status.id === statusId)?.cardSort === "PRIORITY";
const cardsFor = (statusId: string) => cards.value.filter((card) => card.statusId === statusId && !card.archived).sort(sortedByPriority(statusId) ? byPriorityThenPosition : (a, b) => a.position - b.position);
async function toggleStatusSort(status: BoardStatus) { dismissError(); try { await store.setStatusSort(status, status.cardSort === "PRIORITY" ? "MANUAL" : "PRIORITY"); } catch { error.value = "Could not sort this column."; } }
const statusName = (statusId: string) => statuses.value.find((status) => status.id === statusId)?.name || "Status";
const cardAccent = (card: BoardCard) => selectedBoard.value?.pathId ? undefined : pathsStore.activePaths.find((path) => card.pathIds.includes(path.id))?.color || undefined;
const barStyle = (card: BoardCard) => { const position = barPosition(card.startDate || card.dueDate, card.dueDate || card.startDate, visibleDays.value); return position ? { left: `${position.left}%`, width: `${position.width}%` } : {}; };
function selectBoard(id: string) { dismissError(); store.selectedId = id; void router.replace({ query: { ...route.query, board: id } }); void store.loadBoard(); }
// Tabs only switch boards; renaming lives in board settings.
function activateBoardTab(id: string) { if (store.selectedId !== id) selectBoard(id); }
function setView(next: string) { if (view.value === next) return; void router.push({ query: { ...route.query, view: next, ...(next === "gantt" ? { from: ganttFrom.value, to: ganttTo.value } : {}) } }); }
function updateGanttRange() { if (!ganttFrom.value || !ganttTo.value || ganttTo.value < ganttFrom.value) { error.value = "Choose a valid inclusive date range."; return; } error.value = ""; void router.push({ query: { ...route.query, view: "gantt", from: ganttFrom.value, to: ganttTo.value } }); void store.loadGantt(ganttFrom.value, ganttTo.value); }
function shiftGantt(amount: number) { ganttFrom.value = addCalendarDays(ganttFrom.value, amount); ganttTo.value = addCalendarDays(ganttTo.value, amount); updateGanttRange(); }
// Add board lives in the Boards dialog; cancelling New board goes back there.
const newBoardFromManager = ref(false);
function openNewBoard() { newBoard.value = ""; newBoardError.value = ""; newBoardOpen.value = true; }
function openNewBoardFromManager() { managerOpen.value = false; newBoardFromManager.value = true; openNewBoard(); }
function closeNewBoard() { if (store.creatingBoard) return; newBoardOpen.value = false; if (newBoardFromManager.value) { newBoardFromManager.value = false; managerOpen.value = true; } }
// The dialog stays open on failure so the typed name is kept for a retry.
function focusInline(selector: string) { void nextTick(() => { const field = document.querySelector<HTMLInputElement>(selector); field?.focus(); field?.select(); }); }
async function createBoard() { if (store.creatingBoard) return; const name = newBoard.value.trim(); if (!name) { newBoardError.value = "Enter a board name."; focusInline("#new-board-name"); return; } newBoardError.value = ""; dismissError(); try { await store.createBoard(name); newBoard.value = ""; newBoardOpen.value = false; newBoardFromManager.value = false; await router.replace({ query: { ...route.query, board: store.selectedId } }); } catch { newBoardError.value = "Could not create board."; } }
// A column's + adds a blank card at the end of that column and opens it for editing.
async function addCardTo(status: BoardStatus) { if (store.creatingCard) return; dismissError(); try { const card = await store.createCard({ title: "", body: "{}", priority: "MEDIUM", statusId: status.id }); if (card) editCard(card); } catch { error.value = "Could not create card."; } }
function defaultBoardDocument() { return { type: "doc", content: [{ type: "paragraph" }] }; }
function parseBoardBody(body: string) { try { const parsed = JSON.parse(body); return parsed?.type === "doc" ? parsed : defaultBoardDocument(); } catch { return defaultBoardDocument(); } }
function destroyCardEditor() { cardEditor.value?.destroy(); cardEditor.value = null; }
function rememberCardFocus(event: PointerEvent) { const card = (event.target as HTMLElement | null)?.closest<HTMLElement>(".board-card"); if (card) lastFocusedCard.value = card; }
function restoreCardFocus() { const cardId = lastFocusedCardId.value; if (cardId) void nextTick(() => (lastFocusedCard.value || document.getElementById(`board-card-${cardId}`))?.focus()); }
function warnBeforeUnload(event: BeforeUnloadEvent) { if (editing.value && JSON.stringify(draft.value) !== savedSnapshot.value) { event.preventDefault(); event.returnValue = ""; } }
function editCard(card: BoardCard) { clearTimeout(saveTimer); destroyCardEditor(); lastFocusedCardId.value = card.id; editing.value = card; cardDateError.value = ""; saveState.value = ""; saveError.value = ""; closeAnyway.value = false; draft.value = { title: card.title, body: card.body, priority: card.priority, startDate: card.startDate || "", dueDate: card.dueDate || "", pathIds: [...card.pathIds], labelIds: [...card.labelIds] }; savedSnapshot.value = JSON.stringify(draft.value); cardEditor.value = new Editor({ extensions: richTextExtensions(), content: parseBoardBody(card.body), editorProps: { ...richTextEditorProps, attributes: { role: "textbox", "aria-label": "Card body", "aria-multiline": "true" }, handleKeyDown: (_view, event) => { if (event.key !== "Enter" || !(event.metaKey || event.ctrlKey)) return false; void closeEditor(); return true; } }, onUpdate: ({ editor }) => { draft.value.body = JSON.stringify(editor.getJSON()); } }); }
function setDraftDates(value: Date[] | null) { draft.value.startDate = value?.[0] ? format(value[0], "yyyy-MM-dd") : ""; draft.value.dueDate = value?.[1] ? format(value[1], "yyyy-MM-dd") : ""; }
function queueSave() { clearTimeout(saveTimer); saveChain = saveChain.then(persistDraft); return saveChain; }
async function persistDraft() { const card = editing.value; if (!card) return; const snapshot = JSON.stringify(draft.value); if (snapshot === savedSnapshot.value) return; if (draft.value.startDate && draft.value.dueDate && draft.value.dueDate < draft.value.startDate) { cardDateError.value = "Due date must be on or after the start date."; return; } cardDateError.value = ""; saveState.value = "saving"; try { const saved = await store.updateCard(card, { ...draft.value, startDate: draft.value.startDate || undefined, dueDate: draft.value.dueDate || undefined }); if (editing.value?.id === card.id) editing.value = saved; savedSnapshot.value = snapshot; saveState.value = "saved"; saveError.value = ""; closeAnyway.value = false; } catch (saveFailure) { saveState.value = "error"; saveError.value = saveFailure instanceof ApiError && saveFailure.status === 408 ? "The request timed out. Your edits are kept." : saveFailure instanceof ApiError && saveFailure.status === 409 ? "This card changed elsewhere. Retry to save your version." : "Could not save card. Your edits are kept."; } }
async function changeCardStatus(statusId: string) { const card = editing.value; if (!card || card.statusId === statusId) return; saveChain = saveChain.then(async () => { try { await store.moveCard(card, statusId, cardsFor(statusId).length); } catch { error.value = "Could not move card. The change was rolled back."; } }); await saveChain; }
// Closing saves pending edits first; if that save fails the dialog stays open
// with the error, and closing again discards the unsaved edits.
async function closeEditor() { if (!editing.value) return; await queueSave(); if ((saveState.value === "error" || cardDateError.value) && !closeAnyway.value) { closeAnyway.value = true; return; } clearTimeout(saveTimer); destroyCardEditor(); editing.value = null; saveState.value = ""; restoreCardFocus(); }
async function addStatus() { if (!newStatus.value.trim()) return; dismissError(); try { const status = await store.createStatus(newStatus.value, settingsBoardId.value); if (!settingsForOpenBoard.value) otherBoardStatuses.value.push(status); newStatus.value = ""; } catch { error.value = "Could not create status."; } }
function requestArchiveStatus(status: BoardStatus) { archiveStatusConfirm.value = status; }
async function confirmArchiveStatus() { const status = archiveStatusConfirm.value; archiveStatusConfirm.value = null; if (!status || archivingStatusId.value) return; archivingStatusId.value = status.id; try { const boardId = settingsBoardId.value; await store.archiveStatus(status, false, boardId); if (boardId !== store.selectedId) otherBoardStatuses.value = await store.fetchStatuses(boardId); } catch (archiveError) { error.value = archiveError instanceof ApiError && archiveError.status === 409 ? "A board must keep one active status." : "Could not archive status."; } finally { archivingStatusId.value = ""; } }
// Board settings hold the board name and all status management (create,
// rename, reorder, archive) so the Kanban columns stay free of controls.
async function openSettings(id: string) { settingsBoardId.value = id; settingsName.value = boards.value.find((board) => board.id === id)?.name || ""; newStatus.value = ""; otherBoardStatuses.value = []; settingsOpen.value = true; if (id === store.selectedId) return; try { const loaded = await store.fetchStatuses(id); if (settingsBoardId.value === id) otherBoardStatuses.value = loaded; } catch { error.value = "Could not load board statuses."; } }
function closeSettings() { settingsOpen.value = false; settingsFromManager.value = false; }
async function saveSettingsName() { const board = settingsBoard.value; const name = settingsName.value.trim(); if (!board || store.updatingBoard) return; if (!name) { settingsName.value = board.name; return; } if (name === board.name) return; dismissError(); try { await store.updateBoard(board.id, name); } catch { error.value = "Could not rename board."; } }
async function renameStatus(status: BoardStatus, event: Event) { const input = event.target as HTMLInputElement; const name = input.value.trim(); if (!name) { input.value = status.name; return; } if (name === status.name) return; dismissError(); try { await store.updateStatus(status, name, settingsBoardId.value); } catch { input.value = status.name; error.value = "Could not save status."; } }
async function saveStatusOrder(ids: string[]) { try { const saved = await store.reorderStatuses(ids, settingsBoardId.value, settingsAllStatuses.value); if (!settingsForOpenBoard.value) otherBoardStatuses.value = saved; } catch { error.value = "Could not reorder status."; } }
function startStatusDrag(event: PointerEvent, status: BoardStatus) { if (event.button !== 0) return; event.preventDefault(); (event.currentTarget as HTMLElement).setPointerCapture?.(event.pointerId); statusDragId.value = status.id; statusDragOrder.value = settingsActiveStatuses.value.map((item) => item.id); }
function dragStatus(event: PointerEvent) { const order = statusDragOrder.value; if (!statusDragId.value || !order || !settingsStatusList.value) return; const others = [...settingsStatusList.value.querySelectorAll<HTMLElement>("li[data-status-id]")].filter((row) => row.dataset.statusId !== statusDragId.value); const index = others.filter((row) => { const box = row.getBoundingClientRect(); return box.top + box.height / 2 < event.clientY; }).length; const next = order.filter((id) => id !== statusDragId.value); next.splice(index, 0, statusDragId.value); if (next.join() !== order.join()) statusDragOrder.value = next; }
async function endStatusDrag() { const order = statusDragOrder.value; const changed = Boolean(order && order.join() !== settingsActiveStatuses.value.map((item) => item.id).join()); statusDragId.value = ""; statusDragOrder.value = null; if (order && changed) await saveStatusOrder(order); }
async function moveStatus(status: BoardStatus, direction: number) { const index = settingsActiveStatuses.value.findIndex((item) => item.id === status.id); const target = settingsActiveStatuses.value[index + direction]; if (!target) return; await saveStatusOrder(settingsActiveStatuses.value.map((item) => item.id).map((id, itemIndex, ids) => ids[itemIndex] === status.id ? ids[itemIndex + direction] : ids[itemIndex] === target.id ? status.id : id)); }
function dropCard(event: DragEvent, target: BoardCard) { event.stopPropagation(); const cardId = event.dataTransfer?.getData("text/plain"); const card = cards.value.find((item) => item.id === cardId); if (!card || card.id === target.id) return; if (sortedByPriority(target.statusId)) { if (card.statusId !== target.statusId) void store.moveCard(card, target.statusId, cardsFor(target.statusId).length).catch(() => { error.value = "Could not move card. The change was rolled back."; }); return; } const position = cardsFor(target.statusId).findIndex((item) => item.id === target.id); if (position < 0) return; void store.moveCard(card, target.statusId, position).catch(() => { error.value = "Could not reorder card. The change was rolled back."; }); }
async function reorderCard(card: BoardCard, direction: number) { if (sortedByPriority(card.statusId)) return; const column = cardsFor(card.statusId); const index = column.findIndex((item) => item.id === card.id); const target = index + direction; if (index < 0 || target < 0 || target >= column.length) return; try { await store.moveCard(card, card.statusId, target); } catch { error.value = "Could not reorder card. The change was rolled back."; } }
function moveFocusedCard(event: KeyboardEvent) { if (!event.altKey || !["ArrowUp", "ArrowDown"].includes(event.key)) return; const focused = document.activeElement?.closest<HTMLElement>(".board-card"); if (!focused) return; const elements = [...document.querySelectorAll<HTMLElement>(".board-card")]; const index = elements.indexOf(focused); const visible = activeStatuses.value.flatMap((status) => cardsFor(status.id)); const card = visible[index]; if (!card) return; event.preventDefault(); void reorderCard(card, event.key === "ArrowUp" ? -1 : 1); }
function observeSentinel(statusId: string, element: Element | null) { pageObservers.get(statusId)?.disconnect(); if (!element || typeof IntersectionObserver === "undefined" || store.pageCursors[statusId] === null) return; const observer = new IntersectionObserver((entries) => { if (entries.some((entry) => entry.isIntersecting)) void store.loadMore(statusId).catch(() => undefined); }); observer.observe(element); pageObservers.set(statusId, observer); }
// The Boards dialog (the single gear beside Add board) lists every board, opens
// its settings, and pins or reorders any board within its group (pinned or not),
// so custom boards can sit between path boards. The Paths page keeps its own order.
const managerOpen = ref(false), managerDragId = ref(""), managerDragOrder = ref<string[] | null>(null), managerList = ref<HTMLElement | null>(null), pinningBoardId = ref("");
function boardGroup(board: Board) { return boards.value.filter((item) => Boolean(item.pinned) === Boolean(board.pinned)); }
// While a row is dragged the dialog previews the new order within its group; it is saved on release.
const managerBoards = computed(() => { const order = managerDragOrder.value; if (!order) return boards.value; const byId = new Map(boards.value.map((board) => [board.id, board])); const queue = order.map((id) => byId.get(id)!); return boards.value.map((board) => order.includes(board.id) ? queue.shift()! : board); });
function openManager() { managerOpen.value = true; }
function closeManager() { managerOpen.value = false; }
// Settings opened from the Boards dialog offer a Back button that returns to the list.
const settingsFromManager = ref(false);
function openBoardSettings(id: string) { managerOpen.value = false; settingsFromManager.value = true; void openSettings(id); }
function backToManager() { settingsOpen.value = false; settingsFromManager.value = false; managerOpen.value = true; }
function saveGroupOrder(group: Board[]) { store.reorderBoards(group.map((item) => item.id)).catch(() => { error.value = "Could not reorder boards."; }); }
function moveBoard(board: Board, direction: number) { const group = boardGroup(board); const index = group.findIndex((item) => item.id === board.id); const target = index + direction; if (target < 0 || target >= group.length) return; const next = [...group]; [next[index], next[target]] = [next[target], next[index]]; saveGroupOrder(next); }
// The preview moves rows in the DOM, which drops pointer capture, so the drag listens on the window.
function startBoardDrag(event: PointerEvent, board: Board) { if (event.button !== 0) return; event.preventDefault(); managerDragId.value = board.id; managerDragOrder.value = boardGroup(board).map((item) => item.id); window.addEventListener("pointermove", dragBoard); window.addEventListener("pointerup", endBoardDrag); window.addEventListener("pointercancel", endBoardDrag); }
function dragBoard(event: PointerEvent) { const order = managerDragOrder.value; if (!managerDragId.value || !order || !managerList.value) return; const others = [...managerList.value.querySelectorAll<HTMLElement>("li[data-board-id]")].filter((row) => order.includes(row.dataset.boardId || "") && row.dataset.boardId !== managerDragId.value); const index = others.filter((row) => { const box = row.getBoundingClientRect(); return box.top + box.height / 2 < event.clientY; }).length; const next = order.filter((id) => id !== managerDragId.value); next.splice(index, 0, managerDragId.value); if (next.join() !== order.join()) managerDragOrder.value = next; }
function endBoardDrag() { window.removeEventListener("pointermove", dragBoard); window.removeEventListener("pointerup", endBoardDrag); window.removeEventListener("pointercancel", endBoardDrag); const order = managerDragOrder.value; const dragged = boards.value.find((board) => board.id === managerDragId.value); managerDragId.value = ""; managerDragOrder.value = null; if (!order || !dragged || order.join() === boardGroup(dragged).map((item) => item.id).join()) return; const byId = new Map(boards.value.map((board) => [board.id, board])); saveGroupOrder(order.map((id) => byId.get(id)!)); }
async function togglePinned(board: Board) { if (pinningBoardId.value) return; pinningBoardId.value = board.id; dismissError(); try { await store.pinBoard(board.id, !board.pinned); } catch { error.value = board.pinned ? "Could not unpin board." : "Could not pin board."; } finally { pinningBoardId.value = ""; } }
function requestArchiveBoard() { if (settingsBoardId.value) archiveConfirmOpen.value = true; }
function requestArchiveCard(card: BoardCard) { archiveCardConfirm.value = card; }
async function confirmArchiveCard() { const card = archiveCardConfirm.value; archiveCardConfirm.value = null; if (!card) return; try { if (editing.value?.id === card.id) { await queueSave(); clearTimeout(saveTimer); destroyCardEditor(); editing.value = null; } await store.archiveCard(card); } catch { error.value = "Could not archive card."; } }
async function archiveBoard() { const id = settingsBoardId.value; if (!id) return; const wasOpen = id === store.selectedId; archiveConfirmOpen.value = false; settingsOpen.value = false; dismissError(); try { await store.archiveBoard(id); if (wasOpen) await router.replace({ query: {} }); } catch { error.value = "Could not archive board."; } }
onMounted(async () => { measureViewport(); window.addEventListener("resize", measureViewport); document.addEventListener("pointerdown", rememberCardFocus); document.addEventListener("keydown", moveFocusedCard); window.addEventListener("beforeunload", warnBeforeUnload); // The URL's board is selected before the list loads, so loading never falls back to the first tab first.
  const requested = typeof route.query.board === "string" ? route.query.board : ""; if (requested) store.selectedId = requested; await Promise.all([store.loadBoards(), pathsStore.load(), labelsStore.loadScope("BOARD")]); await store.loadBoard(); if (view.value === "gantt") await store.loadGantt(ganttFrom.value, ganttTo.value); });
watch(() => store.selectedId, (id) => { if (id && route.query.board !== id) void router.replace({ query: { ...route.query, board: id } }); if (id && view.value === "gantt") void store.loadGantt(ganttFrom.value, ganttTo.value); });
watch(draft, () => { if (!editing.value) return; clearTimeout(saveTimer); saveTimer = setTimeout(() => void queueSave(), AUTOSAVE_DELAY_MS); }, { deep: true });
watch(view, (next) => { if (next === "gantt") void store.loadGantt(ganttFrom.value, ganttTo.value); });
watch(() => [route.query.from, route.query.to], ([from, to]) => { if (view.value !== "gantt" || typeof from !== "string" || typeof to !== "string" || from === ganttFrom.value && to === ganttTo.value) return; ganttFrom.value = from; ganttTo.value = to; void store.loadGantt(from, to); });
onBeforeUnmount(() => { endBoardDrag(); window.removeEventListener("resize", measureViewport); document.removeEventListener("pointerdown", rememberCardFocus); document.removeEventListener("keydown", moveFocusedCard); window.removeEventListener("beforeunload", warnBeforeUnload); pageObservers.forEach((observer) => observer.disconnect()); clearTimeout(saveTimer); destroyCardEditor(); });
</script>

<template>
  <section ref="boardPage" class="board-page" aria-labelledby="board-heading">
    <h1 id="board-heading" class="sr-only">Boards</h1>
    <div v-if="newBoardOpen" class="dialog-backdrop" role="presentation" @click.self="closeNewBoard"><form v-dialog-focus class="confirm-dialog new-board-dialog" role="dialog" aria-modal="true" aria-labelledby="new-board-title" tabindex="-1" novalidate @submit.prevent="createBoard" @keydown.esc.prevent="closeNewBoard"><h2 id="new-board-title">New board</h2><label for="new-board-name" class="sr-only">New board name</label><input id="new-board-name" v-model="newBoard" name="boardName" placeholder="e.g. Product launch…" maxlength="120" autocomplete="off" :aria-invalid="Boolean(newBoardError)" :aria-describedby="newBoardError ? 'new-board-error' : undefined" /><p v-if="newBoardError" id="new-board-error" class="field-error" role="alert">{{ newBoardError }}</p><div class="editor-actions"><button class="secondary" type="button" :disabled="store.creatingBoard" @click="closeNewBoard">Cancel</button><button type="submit" :aria-busy="store.creatingBoard" :disabled="store.creatingBoard">{{ store.creatingBoard ? "Creating…" : "Create" }}</button></div></form></div>
    <div v-if="managerOpen" class="dialog-backdrop" role="presentation" @click.self="closeManager"><section v-dialog-focus class="confirm-dialog board-settings boards-manager" role="dialog" aria-modal="true" aria-labelledby="boards-manager-title" tabindex="-1" @keydown.esc.prevent="closeManager">
      <header class="board-settings-header"><h2 id="boards-manager-title">Boards</h2><div class="board-settings-heading"><button class="icon-button quiet" type="button" aria-label="Add board" title="Add board" @click="openNewBoardFromManager"><v-icon :icon="mdiPlus" size="20" aria-hidden="true" /></button><button class="icon-button quiet" type="button" aria-label="Close boards" title="Close" @click="closeManager"><v-icon :icon="mdiClose" size="20" aria-hidden="true" /></button></div></header>
      <p id="board-reorder-help" class="sr-only">Drag the handle to reorder, or focus it and press the up or down arrow key. Pinned boards stay first.</p>
      <p v-if="!boards.length" class="column-empty">No boards yet.</p>
      <ul ref="managerList" class="settings-statuses boards-manager-list" :class="{ dragging: managerDragId }" aria-label="Boards">
        <li v-for="board in managerBoards" :key="board.id" :data-board-id="board.id" :class="{ 'is-dragged': managerDragId === board.id }"><button class="icon-button quiet drag-handle" type="button" :aria-label="`Reorder ${board.name}`" aria-describedby="board-reorder-help" title="Drag to reorder" @pointerdown="startBoardDrag($event, board)" @keydown.up.prevent="moveBoard(board, -1)" @keydown.down.prevent="moveBoard(board, 1)"><v-icon :icon="mdiDragVertical" size="20" aria-hidden="true" /></button><button class="boards-manager-name" type="button" @click="openBoardSettings(board.id)"><span v-if="board.pathId" class="board-tab-dot" :style="{ backgroundColor: pathColor(board.pathId) }" aria-hidden="true"></span>{{ board.name }}</button><button class="icon-button quiet boards-manager-pin" :class="{ pinned: board.pinned }" type="button" :aria-pressed="Boolean(board.pinned)" :aria-label="`${board.pinned ? 'Unpin' : 'Pin'} ${board.name}`" :title="board.pinned ? 'Unpin board' : 'Pin board'" :disabled="pinningBoardId === board.id" @click="togglePinned(board)"><v-icon :icon="board.pinned ? mdiPin : mdiPinOutline" size="20" aria-hidden="true" /></button></li>
      </ul>
      <footer class="board-settings-footer end-only"><button type="button" @click="closeManager">Done</button></footer>
    </section></div>
    <div v-if="settingsOpen && settingsBoard" class="dialog-backdrop" role="presentation" @click.self="closeSettings"><section v-dialog-focus class="confirm-dialog board-settings" role="dialog" aria-modal="true" aria-labelledby="board-settings-title" tabindex="-1" @keydown.esc.prevent="closeSettings">
      <header class="board-settings-header"><div class="board-settings-heading"><button v-if="settingsFromManager" class="icon-button quiet" type="button" aria-label="Back to boards" title="Back to boards" @click="backToManager"><v-icon :icon="mdiArrowLeft" size="20" aria-hidden="true" /></button><h2 id="board-settings-title">Board settings</h2></div><button class="icon-button quiet" type="button" aria-label="Close board settings" title="Close" @click="closeSettings"><v-icon :icon="mdiClose" size="20" aria-hidden="true" /></button></header>
      <template v-if="settingsBoard.pathId">
        <h3 class="settings-label">Name</h3>
        <p class="settings-name-readonly">{{ settingsBoard.name }} <RouterLink to="/paths" class="settings-path-link">Rename or hide on Paths</RouterLink></p>
      </template>
      <template v-else>
        <label class="settings-label" for="board-settings-name">Name</label>
        <input id="board-settings-name" v-model="settingsName" class="settings-input" name="boardSettingsName" maxlength="120" autocomplete="off" @keydown.enter.prevent="saveSettingsName" @blur="saveSettingsName" />
      </template>
      <h3 class="settings-label">Statuses</h3>
      <form class="settings-add-status" @submit.prevent="addStatus"><input v-model="newStatus" class="settings-input" aria-label="New status name" name="statusName" placeholder="New status…" maxlength="120" autocomplete="off" /><button class="icon-button quiet" type="submit" aria-label="Add status" title="Add status"><v-icon :icon="mdiPlus" size="20" aria-hidden="true" /></button></form>
      <p id="status-reorder-help" class="sr-only">Drag the handle to reorder, or focus it and press the up or down arrow key.</p>
      <ul ref="settingsStatusList" class="settings-statuses" :class="{ dragging: statusDragId }" aria-label="Statuses">
        <li v-for="status in settingsStatuses" :key="status.id" :data-status-id="status.id" :class="{ 'is-dragged': statusDragId === status.id }"><button class="icon-button quiet drag-handle" type="button" :aria-label="`Reorder ${status.name}`" aria-describedby="status-reorder-help" title="Drag to reorder" @pointerdown="startStatusDrag($event, status)" @pointermove="dragStatus" @pointerup="endStatusDrag" @pointercancel="endStatusDrag" @keydown.up.prevent="moveStatus(status, -1)" @keydown.down.prevent="moveStatus(status, 1)"><v-icon :icon="mdiDragVertical" size="20" aria-hidden="true" /></button><input class="settings-input" :value="status.name" :aria-label="`Status name ${status.name}`" maxlength="120" autocomplete="off" @keydown.enter.prevent="renameStatus(status, $event)" @blur="renameStatus(status, $event)" /><button class="icon-button quiet danger" type="button" :aria-label="`Archive ${status.name} status`" title="Archive status" :disabled="settingsActiveStatuses.length === 1 || archivingStatusId === status.id" @click="requestArchiveStatus(status)"><v-icon :icon="mdiTrashCanOutline" size="20" aria-hidden="true" /></button></li>
      </ul>
      <footer class="board-settings-footer" :class="{ 'end-only': settingsBoard.pathId }"><button v-if="!settingsBoard.pathId" class="quiet danger with-icon" type="button" @click="requestArchiveBoard"><v-icon :icon="mdiTrashCanOutline" size="18" aria-hidden="true" />Archive board</button><button type="button" @click="closeSettings">Done</button></footer>
    </section></div>
    <div v-if="archiveConfirmOpen" class="dialog-backdrop confirm-layer" role="presentation"><div class="confirm-dialog" role="alertdialog" aria-labelledby="archive-board-title" aria-describedby="archive-board-description"><h2 id="archive-board-title">Archive board?</h2><p id="archive-board-description">Cards and statuses stay retained and can be restored later.</p><div class="editor-actions"><button class="secondary" type="button" @click="archiveConfirmOpen = false">Cancel</button><button type="button" :disabled="Boolean(settingsBoardId && store.boardMutations[settingsBoardId])" @click="archiveBoard">Archive</button></div></div></div>
    <div v-if="archiveCardConfirm" class="dialog-backdrop confirm-layer" role="presentation"><div class="confirm-dialog" role="alertdialog" aria-labelledby="archive-card-title" aria-describedby="archive-card-description"><h2 id="archive-card-title">Archive card?</h2><p id="archive-card-description">{{ archiveCardConfirm.title || "Untitled card" }} will remain retained and can be restored later.</p><div class="editor-actions"><button class="secondary" type="button" @click="archiveCardConfirm = null">Cancel</button><button type="button" @click="confirmArchiveCard">Archive</button></div></div></div>
    <div v-if="archiveStatusConfirm" class="dialog-backdrop confirm-layer" role="presentation"><div class="confirm-dialog" role="alertdialog" aria-labelledby="archive-status-title" aria-describedby="archive-status-description"><h2 id="archive-status-title">Archive status?</h2><p id="archive-status-description">{{ archiveStatusConfirm.name }} will be archived and its active cards will move to another status.</p><div class="editor-actions"><button class="secondary" type="button" @click="archiveStatusConfirm = null">Cancel</button><button type="button" :disabled="archivingStatusId === archiveStatusConfirm.id" @click="confirmArchiveStatus">Archive</button></div></div></div>
    <p v-if="error || store.error" class="board-error" role="alert">{{ error || store.error }}<button type="button" class="error-dismiss" aria-label="Dismiss board error" @click="dismissError">×</button></p>
    <div class="board-toolbar">
      <div class="board-tabs" role="group" aria-label="Boards">
        <template v-for="board in boards" :key="board.id">
          <button :class="{ selected: store.selectedId === board.id }" class="board-tab" type="button" :aria-current="store.selectedId === board.id ? 'true' : undefined" @click="activateBoardTab(board.id)"><span v-if="board.pathId" class="board-tab-dot" :style="{ backgroundColor: pathColor(board.pathId) }" aria-hidden="true"></span>{{ board.name }}</button>
        </template>
        <button v-if="!boards.length" class="board-tab empty" disabled type="button">No boards</button>
      </div>
      <div class="board-view-actions"><button class="secondary icon-button manage-boards" type="button" aria-label="Manage boards" title="Manage boards" aria-haspopup="dialog" @click="openManager"><v-icon :icon="mdiCogOutline" size="20" aria-hidden="true" /></button><div class="view-switch" role="group" aria-label="Board view"><button :class="{ selected: view === 'kanban' }" type="button" @click="setView('kanban')">Kanban</button><button :class="{ selected: view === 'gantt' }" type="button" @click="setView('gantt')">Gantt</button></div></div>
    </div>
    <div v-if="loading" class="board-empty" aria-live="polite">Loading board…</div>
    <div v-else-if="!store.selectedId" class="board-empty"><h2>Create your first board</h2><p>Keep projects, priorities, and dates together in one focused workspace.</p><button type="button" @click="openNewBoard">New board…</button></div>
    <template v-else-if="view === 'kanban'">
      <div class="kanban-area" :class="{ wide: kanbanWide }" :style="kanbanWide && viewportWidth ? { '--viewport-width': `${viewportWidth}px`, '--content-left': `${contentLeft}px` } : undefined"><button class="kanban-width-toggle" type="button" :aria-pressed="kanbanWide" :aria-label="kanbanWide ? 'Collapse board to page width' : 'Expand board to full width'" :title="kanbanWide ? 'Collapse to page width' : 'Expand to full width'" @click="toggleKanbanWide"><v-icon :icon="kanbanWide ? mdiArrowCollapseHorizontal : mdiArrowExpandHorizontal" size="16" aria-hidden="true" /></button>
      <div class="kanban" tabindex="0" aria-label="Kanban board">
        <section v-for="status in activeStatuses" :key="status.id" class="kanban-column" :aria-labelledby="`status-${status.id}`" @dragover.prevent @drop="($event) => { const id = ($event as DragEvent).dataTransfer?.getData('text/plain'); const card = cards.find((item) => item.id === id); if (card) void store.moveCard(card, status.id, cardsFor(status.id).length); }"><header><h2 :id="`status-${status.id}`">{{ status.name }}</h2><div class="column-tools"><span>{{ cardsFor(status.id).length }}</span><button type="button" class="column-sort" :class="{ active: status.cardSort === 'PRIORITY' }" :aria-pressed="status.cardSort === 'PRIORITY'" :aria-label="`Sort ${status.name} by priority`" :title="status.cardSort === 'PRIORITY' ? 'Sorted by priority' : 'Sort by priority'" @click="toggleStatusSort(status)"><v-icon :icon="status.cardSort === 'PRIORITY' ? mdiSortDescending : mdiSort" size="18" aria-hidden="true" /></button><button type="button" class="add-card" :aria-label="`Add card to ${status.name}`" :title="`Add card to ${status.name}`" :disabled="store.creatingCard" @click="addCardTo(status)">＋</button></div></header><article v-for="card in cardsFor(status.id)" :key="card.id" class="board-card" :aria-label="card.title ? undefined : 'Untitled card'" :class="{ accented: cardAccent(card) }" :style="{ '--card-accent': cardAccent(card) }" draggable="true" tabindex="0" @dragstart="($event) => ($event as DragEvent).dataTransfer?.setData('text/plain', card.id)" @dragover.prevent @drop.stop="($event) => dropCard($event as DragEvent, card)" @click="editCard(card)" @keydown.enter="editCard(card)"><div class="priority" :class="card.priority.toLowerCase()">{{ card.priority }}</div><h3 v-if="card.title">{{ card.title }}</h3><p v-if="card.startDate || card.dueDate">{{ card.startDate || "Any date" }} → {{ card.dueDate || "Open" }}</p></article><div v-if="store.pageCursors[status.id] !== null" :ref="(element) => observeSentinel(status.id, element as Element | null)" class="load-more-sentinel" aria-hidden="true"></div><button v-if="store.pageErrors[status.id]" type="button" class="secondary page-retry" aria-label="Retry loading cards" @click="store.retryLoadMore(status.id).catch(() => undefined)">Retry loading cards</button><p v-if="!cardsFor(status.id).length" class="column-empty">No cards yet</p></section>
      </div></div>
    </template>
    <section v-else class="gantt" aria-labelledby="gantt-heading">
      <div class="gantt-heading"><div><h2 id="gantt-heading">Timeline</h2><p class="muted">The timeline uses the same active cards as Kanban. Date ranges are inclusive.</p></div><div class="gantt-controls"><button class="secondary" type="button" aria-label="Previous timeline window" @click="shiftGantt(-visibleDays.length)">←</button><label>From<input v-model="ganttFrom" type="date" aria-label="Timeline start date" @change="updateGanttRange" /></label><label>To<input v-model="ganttTo" type="date" aria-label="Timeline end date" @change="updateGanttRange" /></label><button class="secondary" type="button" aria-label="Next timeline window" @click="shiftGantt(visibleDays.length)">→</button></div></div>
      <div class="timeline-scroll" tabindex="0" aria-label="Board card timeline"><div class="timeline" :style="{ minWidth: `${timelineWidth}px` }"><div class="timeline-header"><span class="timeline-label">Card</span><div class="timeline-days" :style="{ gridTemplateColumns: `repeat(${visibleDays.length}, minmax(56px, 1fr))` }"><span v-for="day in visibleDays" :key="day">{{ day.slice(5) }}</span></div></div><div v-for="card in ganttCards" :key="card.id" class="timeline-row"><div class="timeline-label"><strong>{{ card.title }}</strong><small>{{ statusName(card.statusId) }}</small></div><div class="timeline-track"><span v-for="day in visibleDays" :key="day" class="timeline-cell" :class="{ weekend: isWeekend(day) }"></span><button class="timeline-bar" :style="barStyle(card)" type="button" :aria-label="card.title ? undefined : 'Untitled card'" @click="editCard(card)">{{ card.title }}</button></div></div><p v-if="!ganttCards.length" class="board-empty">No dated active cards overlap this timeline window. Cards without dates stay in Kanban.</p></div></div>
    </section>
    <footer class="board-footer"><RouterLink class="link-button secondary with-icon" :to="{ path: '/board/archive', query: store.selectedId ? { board: store.selectedId } : {} }"><v-icon :icon="mdiArchiveOutline" size="18" aria-hidden="true" />Archived items</RouterLink></footer>
    <div v-if="editing" class="dialog-backdrop" role="presentation" @click.self="closeEditor()"><section v-dialog-focus class="card-editor" :class="{ accented: draftAccent }" :style="{ '--card-accent': draftAccent }" role="dialog" aria-modal="true" aria-label="Edit card" tabindex="-1" @keydown.esc.prevent="closeEditor()" @keydown.meta.enter.prevent="closeEditor()" @keydown.ctrl.enter.prevent="closeEditor()">
      <div class="card-meta">
        <select v-if="!selectedBoard?.pathId" :value="draft.pathIds[0] || ''" class="meta-field" name="cardPaths" aria-label="Path" @change="(e) => { const select = e.target as HTMLSelectElement; draft.pathIds = select.value ? [select.value] : []; }"><option value="">No path</option><option v-for="path in pathsStore.activePaths" :key="path.id" :value="path.id">{{ path.name }}</option></select>
        <select v-model="draft.priority" class="meta-field" name="priority" aria-label="Priority"><option value="LOW">Low</option><option value="MEDIUM">Medium</option><option value="HIGH">High</option><option value="URGENT">Urgent</option></select>
        <select :value="editing.statusId" class="meta-field" name="status" aria-label="Status" @change="changeCardStatus(($event.target as HTMLSelectElement).value)"><option v-for="status in activeStatuses" :key="status.id" :value="status.id">{{ status.name }}</option></select>
        <div class="meta-dates"><VueDatePicker :dark="theme === 'dark'" :model-value="draftDates" :range="{ partialRange: true }" :formats="dateFormats" :time-config="{ enableTimePicker: false }" :action-row="{ showCancel: false, showSelect: false, showNow: false, showPreview: false }" :input-attrs="{ clearable: true }" :text-input="false" auto-apply week-start="1" placeholder="Dates" :aria-labels="{ input: 'Card dates', clearInput: 'Clear card dates' }" teleport="body" @update:model-value="setDraftDates" /></div>
        <div v-if="labelsStore.forScope('BOARD').length" class="card-labels" role="group" aria-label="Board labels"><label v-for="label in labelsStore.forScope('BOARD')" :key="label.id" class="label-chip" :class="{ selected: draft.labelIds.includes(label.id) }"><input v-model="draft.labelIds" type="checkbox" :value="label.id" />{{ label.name }}</label></div>
        <button class="icon-button quiet editor-close" type="button" aria-label="Close card" title="Close" @click="closeEditor()"><v-icon :icon="mdiClose" size="20" aria-hidden="true" /></button>
      </div>
      <textarea v-model="draft.title" class="card-title-input" name="title" aria-label="Title" maxlength="240" rows="1" autocomplete="off" @keydown.enter.exact.prevent="cardEditor?.commands.focus('start')"></textarea>
      <EditorContent v-if="cardEditor" class="card-body-editor" :class="RICH_TEXT_CLASS" :editor="cardEditor" />
      <p v-if="cardDateError" class="field-error" role="alert">{{ cardDateError }}</p>
      <p v-if="saveState === 'error'" class="field-error" role="alert">{{ saveError }} <button class="quiet link-like" type="button" @click="queueSave()">Retry</button><span v-if="closeAnyway"> Close again to discard.</span></p>
      <footer class="card-editor-footer"><button class="quiet danger with-icon" type="button" @click="requestArchiveCard(editing)"><v-icon :icon="mdiTrashCanOutline" size="18" aria-hidden="true" />Archive card</button><span class="save-state" aria-live="polite">{{ saveState === "saving" ? "Saving…" : saveState === "saved" ? "Saved" : "" }}</span></footer>
    </section></div>
  </section>
</template>

<style scoped src="./board.css"></style>
